### ISSUE TITLE
Potential image recognition Issues at 3840x2160

### ISSUE THREAD

**Issue by felesmortis** [Lailloken/Lailloken-UI#11]
I'm not completely sure if this is a bug as I've tried reproducing the problem at 1440p and I'm still seeing the same error.

 - I click scan
 - This is where my arrow points ![arrow](https://i.imgur.com/QjECRA8.png)
 - I indicate the mod type for all mods in list
    - even if mods are the same type, I have to select each one individually
 - I can view completable recipes on the right
 - I click scan again, expecting no changes
 - I have to fill out every mod in the list
 - This is my recognition folder (2160p) ![Recognition](https://i.imgur.com/xEcBt3p.png)

**Comment by Lailloken** [comment]
Alright, I think I found the issue. Could you test v1.16.2-beta and see if this bug is fixed? Thank you for the very detailed bug report.

**Comment by felesmortis** [comment]
No problem, thanks for looking into this. It did not appear to work. 

I cleared out the entire Lailloken-UI before copying the new one in in case there was any lingering issues.

I scanned the entire inventory
I hit scan again and it did not skip / recognize anything in the first row. Below is an image of my inventory after the first row of the second scan.
![Second Scan](https://i.imgur.com/LfAfgAx.jpeg)

Recognition folder:
![Recognition 2160](https://i.imgur.com/6TnTsmb.png)

**Comment by Lailloken** [comment]
You have not used this tool before, and this is not an issue that popped up in a recent release, right? Since 1440p isn't working for you either, there might by a problem outside the script. Your image files look fine, the script uses the same coordinates for capturing and searching these, and I have cross-checked with a clean installation as well. It seems to me that the ImageSearch feature in AutoHotkey itself is misbehaving. Could you try reinstalling AutoHotkey?

**Comment by felesmortis** [comment]
Yep. Updating ahk fixed it. Sorry :(

**Comment by Lailloken** [comment]
This issue actually made me find a potentially major bug that I fixed in v1.16.2: the script would inherit the numbers in the .png files when scanning the inventory. These 'corrupted' archnemesis mods would then of course not be assigned to any recipe. A safety measure I had put in previously didn't work correctly. So all of this was actually pretty lucky.
