### ISSUE TITLE
How do I tell Lailloken-UI where the Game Log FIle is?

### ISSUE THREAD

**Issue by lumpyrocks** [Lailloken/Lailloken-UI#116]
I am loving the app so far, but I can't figure out how to get the Mapping Tracker or Levelling Tracker to work. The Mapping Tracker just stays at "Not Tracking 00:00" no matter where I go. I am worried the app can't find the client.txt file, and I can't find anywhere in the installation process to direct it on that file path. Did I miss a step of the installation/set-up? Or is something else going on? Do I have to unzip the file into a specific place?

**Comment by Lailloken** [comment]
The trackers will only show up in the settings menu (and can only be enabled) if the script can find the client.txt on startup. Since you were able to enable these features, the client.txt should not be the problem here. The mapping tracker should be triggered automatically whenever you enter an instance via the map device, and the leveling tracker switches to the next page whenever you enter the location stated in the last bullet point of the current page.

Have you changed the language settings in the game-client to something other than English? I just realized the client.txt logs certain things in the language set in the options, which I have not accounted for and needs to be implemented.

**Comment by lumpyrocks** [comment]
Issue resolved! No i am using english.
I tried opening the CLient.txt fil in notepad, and notepad crashed becasue it was too large. This inspired me to move that file out to a different folder and let POE create a clean client.txt. UI works now!

**Comment by Lailloken** [comment]
Thanks for letting me know. How large was the file? I'm trying to implement error-detection when accessing the file but cannot quite replicate it. I can bloat the client.txt to the point of making text editors crash, but the trackers still work.
