### ISSUE TITLE
shift+wisdom scroll problems

### ISSUE THREAD

**Issue by inspire22** [Lailloken/Lailloken-UI#126]
Thanks for this cool project :)

When trying to get the shift+wisdom scroll working it shows briefly:
Item-info: item not supported

I did get it to show up once, but I'm not sure what I did differently. I'm using old rings+belts I had in my stash.

Long press on middle mouse button does show the window.

Item highlight key is set to alt - should I try changing it?  I closed awakened poe trade to make sure it wasn't messing.

It just worked again on the first ring, but said item not supported on the following ones.

Also, though it's minor increasing the item-info tooltip size, the number stays 0 in the middle, though the tooltip size is changed.

**Comment by inspire22** [comment]
Also how to get f3 to search for the jewel implicit on items? https://github.com/Lailloken/Lailloken-UI/wiki/Context-menu-for-items?  Maybe all that's available there is the 'small' crafting table option.

**Comment by Lailloken** [comment]
> When trying to get the shift+wisdom scroll working it shows briefly:
> Item-info: item not supported

This usually pops up if the item is unidentified, normal rarity, or generally not supported. I have to exclude normal rarity items because otherwise the script can't tell if it copied normal or advanced item descriptions from the client, i.e. whether or not ALT is the correct key for highlighting and advanced descriptions. If it's not, it shows a different message urging the user to check the omni-key settings.

> Item highlight key is set to alt - should I try changing it?

Shouldn't be necessary. The fact that it's showing the 'not supported' message is normal behavior and tells me the inputs it's sending to the client are correct -- you also got it to work in a few instances.

> Also, though it's minor increasing the item-info tooltip size, the number stays 0 in the middle, though the tooltip size is changed.

I usually refer to UI sizes as 'font-size offset' because I scale UIs in line with the font size to prevent misalignment or clipping. So the minus-button decreases the offset by one (the size in the 'general' section of the settings menu being the global point of comparison), the plus-button increases it by one, and the 0-button resets the offset to 0. I changed it to 'size' to sound less strange but forgot to change the layout as well.

> Also how to get f3 to search for the jewel implicit on items?

If you omni-click a cluster jewel it should show the context-menu with 'crafting table: all' and 'crafting table: size'. Clicking 'all' should open the general cluster page on poe.db and a tooltip should be displayed in the middle of the screen asking you to press F3 to use the browser search to highlight the cluster-enchant.

**Comment by Lailloken** [comment]
Did you get it to work correctly, or is there still something wrong?

**Comment by inspire22** [comment]
Thanks!

I was identifying rare rings & belts.  Any idea why they'd not be supported?  Might have been from a few leagues ago since it was in standard, but they were pretty ordinary otherwise.  It only worked maybe 1/15 tries.

UI sizes - works great, I'd just expected the number to change in the middle like the zoom window on chrome.  It makes sense it'd stay 0 to reset it to zero though, so that seems fine.

**Comment by inspire22** [comment]
Thanks!  Yeah I don't know why wasn't working & have been too busy with play around with it further for now.  I'll post a new issue if I have trouble in the new league.
