### ISSUE TITLE
Leveling tracker, gem skill set name

### ISSUE THREAD

**Issue by Pegoth** [Lailloken/Lailloken-UI#129]
Would it be possible to show the source skill set name of the gem when the guide says to purchase it?
Also would like to list every gem instead of just saying press CTRL+F V

Currently it looks like this:

![image](https://user-images.githubusercontent.com/20708012/206269095-b932a9ce-242d-4a38-b93a-c1eb84ae1166.png)

But I'm thinking something like this:

![image](https://user-images.githubusercontent.com/20708012/206270435-537b266b-0a98-44b2-971c-3ee5dbac978c.png)

----

The skill set name I mean:

![image](https://user-images.githubusercontent.com/20708012/206270884-be32d3cf-1dcc-439e-b344-decae524a7cd.png)

Exile-leveling already knows about it and passes it in the "note" property:

![image](https://user-images.githubusercontent.com/20708012/206270650-922c7046-3e81-4bb7-97b7-fd49ab36e352.png)

```json
{
  "type": "gem_step",
  "requiredGem": {
    "id": "Metadata/Items/Gems/SkillGemSplittingSteel",
    "uid": 0.2503280378534358,
    "note": "Level 1-12"
  },
  "rewardType": "quest"
},
{
  "type": "gem_step",
  "requiredGem": {
    "id": "Metadata/Items/Gems/SupportGemChanceToBleed",
    "uid": 0.07273198219231336,
    "note": "Level 1-12"
  },
  "rewardType": "vendor"
},
```

**Comment by Lailloken** [comment]
Hmm, sounds reasonable. I'll need to find a way to prevent the panel from bloating too much, though. For your PoB, what's the highest number of gems that can be purchased at once?

**Comment by Pegoth** [comment]
I think the most is 6 at once (when reaching act 6, Lilly).

**Comment by Lailloken** [comment]
![image](https://user-images.githubusercontent.com/61888437/206366210-aae27a52-888a-4e58-bafb-ca470d58251f.png)

I could add a tooltip to gems to show the skill set name, if that helps. You would still be able to bulk-buy them, and this would give access to this info on-demand at a much later stage (I don't know if that's too relevant because I don't use PoB).

The main problem is panel spacing, as mentioned earlier, but also that the leveling tracker has been in for quite some time: if I take a look into it now, there'll probably be quite a lot that I would want to improve, which I currently don't have the time for.

Let me know what you think.
