### ISSUE TITLE
Item context menu and item info not working

### ISSUE THREAD

**Issue by pmcthor777** [Lailloken/Lailloken-UI#135]
I can't seem to get item info or item context menu working. Every time I omni-click on an item either in my equipment slots, inventory, or stash, it just shows 'no strings for this search'. How do I get these features to work? I'm on v1.29.1 and all screen-check tests return positive.

**Comment by Lailloken** [comment]
The 'no strings' message indicates that the search-strings feature takes precedence, which means the tool cannot copy the item's information for some reason. After omni-clicking an item, try pasting your clipboard into a text-file or something to see what it contains. Are you running PoE as an administrator? There were people who had problems with the client not receiving inputs when running as admin.

**Comment by pmcthor777** [comment]
The clipboard is empty when I paste. I tried running POE and UI in administrative mode, but it's having the same issue.

**Comment by Lailloken** [comment]
I guess manually copying works, right? Did you change anything in the omni-key settings? Because there is a workaround that splits the omni-key into two separate hotkeys, one for items and another one for anything screen-related. Can you copy something random into the clipboard, press the omni-key on an item, and then check if the clipboard gets cleared? If not, the script may not have access to the clipboard.

All that's left is checking everything between the client and the input. Is there some software that would have access to the clipboard? People also had issues with mouse/keyboard software and drivers. Maybe updating AHK helps. The cause of the problem is so simple, yet there isn't much I can do from here as I'm running out of ideas.

**Comment by pmcthor777** [comment]
I didn't change anything for omni-key. The clipboard does get cleared after I press the omni-key on an item. I did manage to get the item context menu to show up if I manually hit ctrl-alt-C on an item.

**Comment by pmcthor777** [comment]
I got the item info to work by clearing the omni-key (items) keybind. It was defaulted to ctrl+alt+c.
