### ISSUE TITLE
Ability To turn off Map Info Module 

### ISSUE THREAD

**Issue by PF-Repository** [Lailloken/Lailloken-UI#137]
I have no clue how to actually turn off the module for map info. It is very annoying being on the screen. Is there some way I can turn this off or some way that you can implement it?

**Comment by Lailloken** [comment]
There's currently no way to disable the feature completely, other than editing map-info.ahk in the modules folder: you can add `return` to line 2.

It never occurred necessary to me to disable it because it's only on screen if you actually use it (well, or accidentally trigger it) and you can fold it in by clicking the lower part. But I can add a disable toggle in the next version.

**Comment by PF-Repository** [comment]
Thanks yea it popped up on my screen and every time i opened my skill tree it was center of screen very odd. But yes a disable button would be great for really any of the function. Sent from my iPhoneOn Dec 8, 2022, at 3:57 PM, Lailloken ***@***.***> wrote:﻿
There's currently no way to disable the feature completely, other than editing map-info.ahk in the modules folder: you can add return to line 2.
It never occurred necessary to me to disable it because it's only on screen if you actually use it (well, or accidentally trigger it) and you can fold it in by clicking the lower part. But I can add a disable toggle in the next version.
