### ISSUE TITLE
can't start it

### ISSUE THREAD

**Issue by danteafk** [Lailloken/Lailloken-UI#140]
getting this error even though i'm windowed fullscreen. my resolution is 5120x1440p

![image](https://user-images.githubusercontent.com/18619612/206616070-7dbe837e-b3e7-4ba8-a375-590d3d2edadc.png)

**Comment by Lailloken** [comment]
Do you have multiple clients installed? Or multiple users on the PC? I've had reports in the past where users had the same problem, but they never told me how they fixed it. It was always: "oh nevermind, I was running the wrong client." or "oh, I was running the script as the wrong user."

Could you check the 'production_config.ini' file (it's in the folder where lootfilters go)? If there's a line "fullscreen=true", change it to "fullscreen=false".

**Comment by Hillgrove** [comment]
same issue.. I'm using a limited account to run POE as I've heard too many examples of people getting banned for trade apps etc.

**Comment by Lailloken** [comment]
I'm not sure how limited accounts work. What the script is trying to determine by reading the PoE config is which window-mode the client is currently running. Exclusive windowed mode doesn't work, so that's why there's the warning. If it's running in windowed mode, the script has to offset the screen coordinates and window-size slightly so that everyting is in the right place.

The script is probably reading the incorrect config file (I assume there's a separate user\documents folder for limited users?), so maybe edit both manually so they have the same "fullscreen=false" and "borderless_windowed_fullscreen=true" (or whichever setting is correct for your setup).

**Comment by Hillgrove** [comment]
> I'm not sure how limited accounts work. 
Basically when run with a limited user, PoE.exe only has access to that users documents, %appdate% PoE's own folder.

The script will look at my main account's  'production_config.ini' file (which I've change to Fullscreen=False allowing me to get a step further).
 
> The script is probably reading the incorrect config file (I assume there's a separate user\documents folder for limited users?), 

correct. I've changed the file the script is looking at (unless it looks at other files as well).

> so maybe edit both manually so they have the same "fullscreen=false" and "borderless_windowed_fullscreen=true" (or whichever setting is correct for your setup).
I didn't catch the "borderless_windowed_fullscreen=true" setting the first time around.. I'll give it a shot when I'm done re-installing PoE (just in case).

**Comment by Lailloken** [comment]
Whoopsie. I was about to implement an override to enable manually picking which config-file to use, but then I noticed that such an override already exists. Users can add the following to the [Settings] section of the config.ini file:

![image](https://user-images.githubusercontent.com/61888437/207059332-2bddf190-17c1-4637-ace6-67c50bf5b6ae.png)

I implemented this a few months ago and completely forgot about it.
