### ISSUE TITLE
Support for 1440p unsupported resolutions.

### ISSUE THREAD

**Issue by lukezamboni** [Lailloken/Lailloken-UI#141]
Please allow 1440p based ultra-wide resolutions as these are the most common ultra-wide resolutions, being more used than 16:9 4k according to https://levvvel.com/gaming-monitor-study-2022/

**Comment by Lailloken** [comment]
As long as the vertical resolution is a standard (720p, 900p, 1080p, 1200p, 1440p, etc.), there shouldn't be a problem, no matter how wide the monitor. Does the script not launch on your setup?

![image](https://user-images.githubusercontent.com/61888437/206652425-0d7584e8-53aa-4a0e-be8f-f2e0851b3cfe.png)

**Comment by lukezamboni** [comment]
I run an unsupported resolution so it asks me to select a custom resolution
before it launches.

The dropdown for custom resolutions only goes up 1200 so I end up with a
lot of monitor empty.

**Comment by Lailloken** [comment]
So you're running the game in windowed mode then? The tool checks the vertical resolution on launch and sets the maximum selectable based on that. You're game is not running at 1440p, so the next step down that is supported is 1200p.

The reason why vertical resolution is restricted to these standards is that the game-client renders certain UI elements inconsistently at uncommon resolutions. This tool started as an archnemesis recipe scanner, and there were so many users who had problems with scanning because of their resolution. These inconsistencies make screen-reading impossible and some features unusable. I'm offering users of uncommon resolutions a compromise solution to run the client at a supported one. It's either this or not being able to use the tool at all.

Why aren't you running at full resolution?

**Comment by lukezamboni** [comment]
Yes it's in window mode so the official resolution ends up at 1396 I
believe. I can check if full screen works and I'd be fine with that.

I prefer running PoE in windowed just because of the flexibility of having
the task bar below, but I don't mind testing out full screen and sticking
to that if it works.

I'll try in a few hours and report back.

**Comment by Hillgrove** [comment]
I'm running at 3440 x 1440 and got the same issue (windowed fullscreen due to easier alt-tabbing)

![image](https://user-images.githubusercontent.com/20029330/206726624-4074a514-8976-405c-8045-7cad4cef7a53.png)

Do I have to run it in regular fullscreen?

**Comment by lukezamboni** [comment]
I am running Windowed Fullscreen without any issues. maybe try deleting the script folder and starting over. I had to do it after changing to fullscreen.

**Comment by Lailloken** [comment]
> Not sure if it matters, but I'm using this script to fix GGG's crappy widescreen

Huh, 3440 widescreen also has black bars? 

> Do I have to run it in regular fullscreen?

No, that won't work.

The problem is that the script probably thinks the client is running in windowed mode. Windows in windowed mode have a border, that's why the message is showing 1401p (it subtracts the usual border height from the current window height). This is caused by reading the setting in the PoE config incorrectly. Either it's reading the wrong file again (in the other thread, you mentioned limiter user-accounts), or something else is wrong. Did you click 'save' in the in-game options? Maybe jump back and forth between windowed and fullscreen-windowed, then click save and restart the script.

**Comment by lukezamboni** [comment]
3440x1440 gets black bars on window mode since the ratio is forced to be bigger than 21:9.

**Comment by Lailloken** [comment]
To be clear (I need to know because yesterday's release included a fix for black bars):
a client in windowed mode on a 3440x1440 monitor has black bars because the client-resolution will be something like 3440x1400, right?
When I implemented the fix yesterday, I was assuming 24:10 to be the maximum aspect ratio.

**Comment by Hillgrove** [comment]
I'm reinstalling PoE atm to test 3440 x 1440 without the previous linked script (not sure if it's needed anymore).

I'll report back when it's done.

**Comment by Hillgrove** [comment]
Reinstalling and changing "fullscreen=false" and "borderless_windowed_fullscreen=true" did the trick (tbh I think it was mainly the missing "borderless_windowed_fullscreen=true".

I don't use the widescreen fix anymore (and no black borders) on 3440 x 1440.

**Comment by lukezamboni** [comment]
> 3440x1440 monitor has black bars because the client-resolution will be something like 3440x1400, right? 

to be precise its 3440x1369
