### ISSUE TITLE
Error at line 21

### ISSUE THREAD

**Issue by Oldmate88** [Lailloken/Lailloken-UI#143]
![Capture](https://user-images.githubusercontent.com/120177917/206685264-28df918b-4fe9-47c1-a8ae-b959b3ef0fc1.PNG)

Not sure if i am doing something wrong here?

**Comment by Lailloken** [comment]
It's possible the AutoHotkey install on your system is outdated.

**Comment by killersquad235** [comment]
I got the same Issue.
Downloaded ahk fresh and still got the Error.

**Comment by killersquad235** [comment]
Got the same Issue
Problem solving: simply unzip the File.

**Comment by kung69** [comment]
Got the same problem. AHK installation was updated today, error message stays the same

**Comment by Lailloken** [comment]
killersquad234 mentioned that this error occurs when running the script from the zip file, and I can confirm it. So make sure to unzip the script folder correctly and run it afterwards.

**Comment by kung69** [comment]
> killersquad235 mentioned that this error occurs when running the script from the zip file, and I can confirm it. So make sure to unzip the script folder correctly and run it afterwards.

It is unzipped. I tried running the release before the latest and get another error in another line. then overwrote it with the newest one again, now i get
![image](https://user-images.githubusercontent.com/62521122/206763422-6c19873a-0703-4978-976e-1b5ef17a60fd.png)

Script also run in admin-mode, no change. is the poe-client needed running maybe? I have the client running, but I#m in the cue for leaguestart, may that cause the issue? tried my other ahk-scripts and they run without problems.

**Comment by Lailloken** [comment]
No, the game-client is not required. This new error message is definitely because of an outdated AutoHotkey installation, there have been many cases in the past. Recently, someone also thought they had updated their AHK installation, but then the script was opened with an older version all the time. Maybe you have the same issue. I don't know how that happens, but maybe check if there are two installations for some reason. Or manually unistall AHK, delete the folder, and install it fresh.

**Comment by kung69** [comment]
there was only one properly installed, but still the script used another one, i searched  and deleted all ahk-installations manually and reinstalled the newest from their website. It works now, thank you very much!
