### ISSUE TITLE
Script could not create some required folders

### ISSUE THREAD

**Issue by JamieBunpup** [Lailloken/Lailloken-UI#148]
Hey there, I have this issue happening and I have made absolutely sure I have permissions set in the folder I put the script in.

Are there any other folders I should be aware of? Maybe folders on C drive the programs tries to create?

I can't see any other issue threads on this so I guess I'm the only one?

I have also tried disabling bitdefender and attempting to run the script and running the script itself in administrator and setting Autohotkey to run with administrator mode.
![NVIDIA_Share_tplKr4jsOw](https://user-images.githubusercontent.com/71115700/206813935-9004e8ab-1200-4ef1-acad-9c31828d3471.png)

**Comment by Lailloken** [comment]
It tries to create sub-folder to store image captures for screen-reading. There have been a few reports of features not working correctly in the past week, and it was always due to missing write-permissions. A few people resolved it by moving the script folder somewhere else (e.g. out of the program files folder), others stated "it was due to admin rights" but didn't clarify what they did to resolve it.

**Comment by Lailloken** [comment]
You can try this experimental version: https://github.com/Lailloken/Lailloken-UI/archive/refs/heads/experimental.zip

**Comment by CrystalDave** [comment]
I'm also running into this, tested across different drives/locations. I think the issue as I'm running into it is some files within the folder having the read-only flag stuck on. (i.e. it persists even when I toggle it off)
It's probably some local setting/issue I haven't found a solution for, but I figure it's worth mentioning in case that helps narrow it down/suggests a different approach than the exhaustive/band-aid fix.

If I figure out a solution I'll report back, of course.

**Comment by Lailloken** [comment]
> I think the issue as I'm running into it is some files within the folder having the read-only flag stuck on.

I just noticed that this is the case on my end as well.

> but this is what fixed it for me

Glad you found a solution, but I don't think I can expect the average user to do that.

I also went through the possible fix (blank folders and ini-files) in my head, and I don't think it's a good solution after all. I would have to include the ini-files in a separate folder because including them in the regular ini folder would cause the user's ini-files and their settings to be overwritten whenever there's an update. Everytime I implement a new feature, affected users would also have to move its ini-file from this 'sample ini folder' into the regular one. If they forget (or don't read release notes), the feature won't work correctly and they will submit bug reports.

So the only feasible solution seems to be keeping things as they are at the moment: moving the folder around until it has sufficient write-permissions, or running it as administrator.

**Comment by JamieBunpup** [comment]
>it was some sort of weird lingering permissions issue from reinstalling Windows a bit back.

This is exactly what's been happening to me. It's been very frustrating and I have tried many times to change permissions and it does apply but read only is stuck, it's been incredibly annoying and I haven't experienced this before and I re-format every 3-6 months.


>icacls "E:\Lailloken-UI\" /reset /T /L /Q
takeown /f "E:\Lailloken-UI\" /r /d Y
attrib -r -h -s "E:\Lailloken-UI" /s /d


I might give this a try.

**Comment by Lailloken** [comment]
@JamieBunpup How are you starting it as administrator? By right-clicking and selecting 'run as admin', or by setting run as admin in the properties of the AutoHotkey.exe file in the AHK installation on your system? I'm asking because there were several reports where people somehow ended up with multiple AHK installations on their system and the script would always run with the outdated one. Maybe it's something similar in your case, only that the non-admin one is starting? Grasping for straws here, but you did mention you reformat every so often.

**Comment by JamieBunpup** [comment]
I have tried both to no effect. I also can confirm setting the Autohotkey executable did run it as admin as the prompt appeared to give it permission to run as admin when running the ahk script without right clicking and clicking "Run as administrator"

**Comment by Lailloken** [comment]
Well, crap. Let's beta-test the band-aid fix then: https://github.com/Lailloken/Lailloken-UI/archive/refs/heads/experimental.zip

1. rename the included "_ini" folder to "ini"
2. open the "img" folder, and rename the "_Fallback" folder inside to "Recognition (XXXXp)" -- XXXXp being your vertical resolution, e.g. 1080p, 1440p, etc.
3. Launch the script. Open the settings menu by clicking the LLK-UI panel (top-left corner by default) and increase the interface-size significantly (just to see if the settings are saved correctly).
4. Restart the script by right-clicking the LLK-UI panel. If the UI-size is still large, the settings were saved correctly and **at least** this part of the band-aid fix is working.

You'll have to see if the features you want to use work correctly on a case-by-case basis because most features have their own ini-files (and the write-permission reports from the past week indicated that some ini-files were accessible while others weren't). I also don't know if your system will let the script save/create new calibration files for screen-reading. For some poeple, the script was only prevented from creating the folders but not from creating the files inside (once the folders were created manually). It may be different on your end.

**Comment by JamieBunpup** [comment]
I have just tried this out and it did work, though i am now on act 10 but I will give it a spin for this last act. I just wanted to help you resolve this issue and confirm the fix is working thus far, will report back with features that are and aren't working

**Comment by Esionru** [comment]
same problem, nothing helped

**Comment by Lailloken** [comment]
@Esionru Try the fix from my latest comment, it worked for JamieBunpup.
