### ISSUE TITLE
See there is function for NVIDIA GeForce NOW, is it hard to do same for Boosteroid?

### ISSUE THREAD

**Issue by DarkStas** [Lailloken/Lailloken-UI#159]
Could it be make to work with Boosteroid? (or ported)

**Comment by Lailloken** [comment]
I had to check because I have never heard of it. Is it just running in a normal browser or does it also have a client? If it's just running in a browser, it might be difficult to always find the correct window.

If it doesn't have a client and only runs in web-browsers, one solution could be to install a secondary web-browser that you only use for boosteroid. The script could then be modified to handle this browser as the game-client and apply overlays, etc.

That said, I don't know how many of the script's features actually work for streaming services. GeForce Now support was added at the very beginning when the script was only scanning the screen for archnemesis recipes, and since then I have added many features but haven't received much feedback on what works and what doesn't.

**Comment by DarkStas** [comment]
It runs with a client. Boosteroid.exe
I tried to change in code GeForceNOW.exe to Boosteroid.exe but it do nothing, only if needed update it showed me overlays (for 1 sec in the upper left corner and not reacting to anything overlay for update).

But I would to say, if it need more that 30 min to try to make it work with Boosteroid, there no need for it.

**Comment by Lailloken** [comment]
I double-checked, and I think there's a missing line around line 40 in the main ahk-file:

`GroupAdd, poe_window, ahk_exe GeForceNOW.exe`
`GroupAdd, poe_window, ahk_class POEWindowClass`
`GroupAdd, poe_ahk_window, ahk_class POEWindowClass`
`GroupAdd, poe_ahk_window, ahk_exe GeForceNOW.exe` <--- this one
`GroupAdd, poe_ahk_window, ahk_class AutoHotkeyGUI`

There is also a GeForceNow.exe line in "modules\settings menu.ahk" that needs to be changed to boosteroid.

**Comment by DarkStas** [comment]
One time it showed me "positive" in gamescreen but then never after.

**Comment by DarkStas** [comment]
I understand, this don't work if I'm in Boosteroid and it's the "center screen", but if I click and select the options screen as the "center screen" then pixel check works (game as a background of option menu of script).

**Comment by DarkStas** [comment]
One more question, can't move item because it sending them to chat. 
What options is it, what it trying to do, and how it off?

**Comment by DarkStas** [comment]
And one more problem, in betrayal menu do not work prio-view options.

**Comment by DarkStas** [comment]
Cant get how to use recognize so will do it with hands.
There some minor inconvenience, when I press mouse on the script overlay and it to something mouse will teleport to some degree.

**Comment by Lailloken** [comment]
You could try this: in the modules folder, there is a hotkeys.ahk file which is empty. Add these lines
`~RButton UP::`
`~LButton UP::`
`WinActivate, ahk_exe boosteroid.exe`
`Return`

This will focus the boosteroid client everytime you release left or right mouse-button while boosteroid or a script overlay is active. I don't know if this has negative side-effects, but it's the only thing that comes to mind right now that would fix the teleporting cursor.

**Comment by DarkStas** [comment]
Not helped. But Thanks, its already good that it is working.
