### ISSUE TITLE
Bad choice of buttons for sanctum overlay

### ISSUE THREAD

**Issue by worldendDominator** [Lailloken/Lailloken-UI#163]
Right + middle mouse buttons is a very inconvenient choice of keys - I end up triggering it by accident all the time while fighting and it locks up my screen for a several seconds.

**Comment by Lailloken** [comment]
Ah crap, a combination of unfortunate circumstances. Sorry about that.
1. I would have used CTRL+ALT+omni-key like for betrayal, but someone reported that this combination doesn't work in certain configurations. It probably happens because one of the modifier-keys is blocked by another key-combination, so I chose something that can't be (right-click).
2. The "gamescreen" pixel-check should prevent triggering any omni-key feature by accident, but not everyone plays with the minimap in overlay-mode all the time.

Thanks for reporting, I'll fix it shortly.

**Comment by Lailloken** [comment]
I changed the sanctum image-check in v1.29.4-hotfix1 to prevent that from happening. I hope that improves things.
