### ISSUE TITLE
Stash search rarely works

### ISSUE THREAD

**Issue by dovry** [Lailloken/Lailloken-UI#183]
I have gotten it to work before, but never reliably. It's usually only on the first attempt after a fresh boot.

Latest update, I run the script with a shortcut to this powershell script

    git pull
    & '.\Lailloken UI.ahk'

Screen check shows stash test as positive

![image](https://user-images.githubusercontent.com/15201298/211650414-9f4fbd89-c4ea-458d-8d83-e06821010625.png)

omni key works elsewhere

![image](https://user-images.githubusercontent.com/15201298/211650602-82fbe61f-14f9-4140-ab82-313150f055a5.png)

Search strings
![image](https://user-images.githubusercontent.com/15201298/211650760-43a8b7ad-c1b7-40df-a25b-e4abff0359e5.png)
![image](https://user-images.githubusercontent.com/15201298/211650824-9279d06e-7d16-4184-ad1d-5cd0e608ee57.png)

**Comment by Lailloken** [comment]
Hmm, it's possible that something is wrong with the 'gamescreen' pixel-check. Whenever the omni-key is pressed while **not** hovering an item, the script checks the status of that check to decide whether the screen needs to be read for specific UI elements (in this case, it would be the stash plaque). The screen-reading itself seems to be working since manually testing the image-check returns positive results, so the problem occurs prior to it.

Try re-calibrating the 'gamescreen' pixel-check to see if that fixes anything.

**Comment by dovry** [comment]
That was it, Thanks.

I assumed that the script did this when it launched because sometimes it resizes the client window if I've dragged or resized it.
![image](https://user-images.githubusercontent.com/15201298/211759755-0f037b29-7488-4506-961b-0d6a6c46ab26.png)
