### ISSUE TITLE
Map info bug with atlas memories

### ISSUE THREAD

**Issue by worldendDominator** [Lailloken/Lailloken-UI#197]
I've map-info'd the map offered by Kirac for memory of Phaaryl. This is the result:
![изображение](https://user-images.githubusercontent.com/6707627/225278256-8ce62509-0133-4c9e-89de-2c60dc36a171.png)
First, the info panel doesn't apply the map's "increased magnitude of explicit modifiers" (compare +100% aoe in the info panel and +145% in-game). Second, for some reason it catches "harbingers have increased cooldown recovery" as "player has less cooldown recovery" (there's both 75% less cdr and 40% less cdr in the info panel).

Also, trying to right click the info panel header (which normally brings up the window for changing mod highlight) gives me this error message:
![изображение](https://user-images.githubusercontent.com/6707627/225278326-b6c8f44f-2e97-410f-a496-5131e62149b4.png)

I haven't checked with other memory types, but I will do it later.

**Comment by Lailloken** [comment]
Oh, I have never used memories, so they're not really supported right now. Thanks for reporting, I'll see what needs to be done.

**Comment by worldendDominator** [comment]
![изображение](https://user-images.githubusercontent.com/6707627/225288939-d431146c-866a-4606-aa2b-3527dd7c5822.png)
Niko's memory of grasping hands: breach aoe and breach monster life become monster aoe and %es.

**Comment by worldendDominator** [comment]
![изображение](https://user-images.githubusercontent.com/6707627/225366325-b5651cc2-6fb0-4ec7-bf53-3ddbc8610397.png)
Niko's memory of tormented souls: two "possessed" lines. Same error message as in the opening post.

**Comment by Lailloken** [comment]
Thanks for doing this, but I don't need any more specific cases for now. The map-info panel was implemented quite some time before memories entered the game, and the bugs are a result of simple oversight because I have never used one (as mentioned earlier). I'll have to look up all the possible mods and conflicts with regular map mods, then figure out how to present that.

I was going to re-do the panel anyway (and maybe implement heist, as you requested), and now I know from the get-go that memories have to be considered as well.

**Comment by Lailloken** [comment]
Finally found some time to rework the map-info panel. Here's some progress and thoughts:

![image](https://user-images.githubusercontent.com/61888437/228555502-2be56b79-6d2b-4cb5-b6f3-1484091b4f83.png)
![image](https://user-images.githubusercontent.com/61888437/228559590-3d865e06-a58c-4218-bade-1bfa067c7092.png)

- ignore the wording on the mods for now, not final

- the panel now has two different steps and it's no longer permanently on screen
  - if you omni-click a map, the panel will open near the cursor: you can long-click mods and then press 1-4 to apply highlight-colors, or right-click them to gray them out

  - after closing it, you can double-tap ALT (key may change, but unlikely) to show the panel on the right edge of the screen for the duration of holding down ALT: mods that were grayed out are now completely hidden

- the first row shows # of mods, quant, rarity, pack size
- it now takes into account increased magnitudes and implicits that are also regular map mods (monster life & dmg in the image) and adds the values together, but it ignores implicits/enchants that are highly specific
  - IMO, it makes little sense to include these specific implicits/enchants -- neither for highlighting (you can't re-roll to avoid them), nor as a reminder (if you do these memories, you're pretty much familiar with what they do because you prepare beforehand)

  - need feedback on that

- will add heist support when I finalize the wording for the mods

**Comment by Lailloken** [comment]
v1.30.2 should fix the issues
