### ISSUE TITLE
Game runs in 1440p using borderless gaming, but app detects normal window size

### ISSUE THREAD

**Issue by ViolentSempie** [Lailloken/Lailloken-UI#226]
I'm using windowed borderless gaming to force the game to run windowed fullscreen without black borders. this means the full resolution is 2560x1440, however, LLK-UI detects 1408 vertical pixels, which is wrong. I also can't select 1440p as custom resolution, only 1200p.

anyway I can tell it that my resolution is correct?

**Comment by Lailloken** [comment]
Can you send me a screenshot of what that looks like? Do you mean you so can see the desktop underneath?
![image](https://user-images.githubusercontent.com/61888437/230679492-3ecf6d60-29a7-474c-8587-3e0e16434ff5.png)

If you do mean that, you can set that up in my tool as well.

**Comment by Lailloken** [comment]
I'll be in bed soon, so there won't be any response for now. I don't understand the part "without black borders". So you're trying to run 2560x1440 on what kind of monitor?

**Comment by ViolentSempie** [comment]
Hi, no problem, get some sleep!

So here's my setup. I run a Samsung Odyssey G9 32:9 5120x1440 screen. However, when I run the game in windowed fullscreen, I get black borders on the side. To avoid this, I run the game in windowed mode and use an app called "Borderless gaming" that forces the game to run without borders. This makes it so that I don't have the title bar and borders around my game and it runs perfectly in 2560x1440p. I've attached a screenshot on how this looks, including the in-game settings screen that shows the resolution.

![image](https://user-images.githubusercontent.com/3692135/230682273-0eb7e6bf-d852-4079-8588-bba2f624b880.png)

as you cans ee, the game runs at 12560x1440p, a supported resolution. However, when I then run the AHK script, it says this: 
![image](https://user-images.githubusercontent.com/3692135/230682471-6319dda3-1b01-42a0-bd7b-5baf9a2f96a0.png)

as you can see, the game says it detects 1408 pixels, but in reality it's running in 1440p.

**Comment by Lailloken** [comment]
Gotcha, you're running a 32:9 monitor. The resolution detection gets thrown off because it first checks the window-mode settings as configured in the game's settings menu. Since it has to be set to "windowed" for your usecase, the script assumes that the measured 1440 pixels include window borders.

I guess you can trick the script by creating a copy of your PoE-config file ("production_config.ini", located in the folder where lootfilters are), and editing it to include `fullscreen=false` and `borderless_windowed_fullscreen=true`. Then save it, and edit the script's config file (ini\config.ini). There's a line 'PoE config-file="X:\yadda yadda\Path of Exile\production_config.ini"` that can be changed so that the script reads a different PoE config-file. This is usually for people who run PoE as a different Windows user-account, which would make the script read the wrong config-file.

**Comment by ViolentSempie** [comment]
Thank you! this works great!
