### ISSUE TITLE
Skilltree screencheck and omni key not working

### ISSUE THREAD

**Issue by skudrq** [Lailloken/Lailloken-UI#230]
Hey, I'm a first time user. I did Inventory and Gamescreen checks without a problem but whenever I try to do skilltree check, I use the snippet tool as instructed, the file is created under the image folder (img\Recognition (1440p)\GUI) but it is still a negative whatever I do. I also tried to use omni keys to search for gems while leveling but it doesnt work for me. I tried the default keybind (middle click) and even tried to rebind but none of them works. Any ideas?

**Comment by Lailloken** [comment]
- Are you on a regular 2560x1440 monitor?
- Have you double-checked the gamescreen test (toggling the map to fullscreen, test should be positive, toggling it to top-right corner should be negative)?
- Are you using some kind of graphics filter, like Nvidia sharpening or ReShade?
- can you send me the skilltree img-file?

**Comment by skudrq** [comment]
I'm on a ultrawide screen, 3440x1440
Gamescreen and Inventory checks works without a problem, as you have said, it is positive when map is fullscreen and negative when minimized. I'm not using any filters. Github doesnt allow uploading of BMF Files so hope this works.


![18sez8b](https://user-images.githubusercontent.com/130231010/230727374-4059814f-3dd2-40ad-a1c8-29ad9b2125e5.png)
![4Iim70x](https://user-images.githubusercontent.com/130231010/230727383-288ea28b-d194-4505-ad89-9ab1f2b75aa9.jpeg)

**Comment by Lailloken** [comment]
Strange, it works for me when I force an UltraWide 1440p resolution on my 16:9 monitor -- I can use the skilltree overlay without issues, and recalibrating and re-testing works every time (ignore the image in the overlay):
![image](https://user-images.githubusercontent.com/61888437/230728012-e3c49c9d-c66a-40ca-b2fd-930d5aae493e.png)

Could you right-click the L-icon in the system tray and click help in order to check you AHK version? I think there was someone in the past who couldn't get positive screen-checks because of an outdated AHK version.

**Comment by skudrq** [comment]
It is 1.1.36.02
How about the omni button not working, would it be AHK related?

**Comment by skudrq** [comment]
Oh okay, I just run the script file as admin and it fixed it, sorry to bother you :(

**Comment by Lailloken** [comment]
no worries, glad it worked out
