### ISSUE TITLE
Archnemesis window detection isn't working reliably

### ISSUE THREAD

**Issue by rocketmantis** [Lailloken/Lailloken-UI#24]
Hi, using 1.20.4 here. When I can get the tool to appear, it works great -- but whatever system you're using to detect the Archnemesis window doesn't usually work for me. If I delete my config file, I can get the bottom (alphabetical) window to appear... but only if I mouse over one of the recipe tokens so its tooltip is open. The initial scan works fine, after that.

I can pick recipes and stuff for that first session okay, as long as I continue to mouse over an item and then quickly click the recipe I want. But once that first window is closed, even mousing over items to show the tooltip doesn't bring back the GUI.

From poking at the code, it looks like you're using text detection for the word "Archnemesis" on the screen, is that right? I guess it's supposed to pick up the text in the header? I do have ReShade running, but I tried turning it off and the problem still persists.

Is there a way I can lower the sensitivity on the text detection, or have a hotkey to force the GUI open, or something like that?

**Comment by Lailloken** [comment]
This is how the detection works:
![pixel](https://user-images.githubusercontent.com/61888437/155480484-314b2eb1-7d60-4d1c-af75-eb9a7f316a50.jpg)
When you set up the script for the first time, it asks you to open the inventory, move the mouse away from it, then press the 7-key. What the script does is take the color values of two pixels (see picture) at the time the 7-key is pressed. From now on, the script checks the color of the first pixel in the background, and whenever it matches, it checks the second one (this is a safety measure in case the first value randomly matches even if the inventory is not open).

You are probably using an adaptive filter or something similar which causes the color of these pixels to change inconsistently, i.e. it changes from, for example, brown to red-brown in one situation and from brown to orange-brown in another. This impacts the detection in the script, leading to it not properly recognizing when the inventory is open.

I implemented a fallback feature in v1.20.4 for people who have performance problems with the background-scanning but it wouldn't help in this situation. I could implement a hotkey toggle if you want, but this impacts the archnemesis gameplay loop: you click the statue, inventory opens -> you toggle the overlay with a key -> you put a mod inside, start the encounter -> the inventory closes automatically, but the overlay stays up -> you have to toggle it again. It's the same if you get attacked while navigating the inventory: inventory is open, you get attacked, you move or do any other action -> inventory closes, overlay stays open. Worst case, you can't move because you click something on the overlay.
I would suggest you adjust or disable ReShade for PoE because I would have to change the core mechanism of the overlay and split it into two branches that would have to be maintained individually from now on. And all this to accomodate cosmetic graphical filters, not even performance issues (as in 1.20.4).

**Comment by rocketmantis** [comment]
Fair enough!
