### ISSUE TITLE
Track kills per map ?

### ISSUE THREAD

**Issue by bi0hazard6** [Lailloken/Lailloken-UI#251]
Hi,

I have a similar issue. My kill command result does not have the comma as thousands seperator. Each time i finish a map, I get 0 kill.

Do you need more info? Is this a bug?

### Discussed in https://github.com/Lailloken/Lailloken-UI/discussions/120

<div type='discussions-op-text'>

<sup>Originally posted by **GrimDawn-max** November 12, 2022</sup>
Could you add a feature that tracks kills per map and include it in the loot stats export file. The stat exists manually of course via the /kills command but you also have to remember to execute it before you kill anything in a map and again at the end so an automated way to do so would be handy.</div>

**Comment by Lailloken** [comment]
Can you upload a screenshot of when you first click the flashing timer after entering a new map, and another one of when you click it again after exiting a map?
![image](https://user-images.githubusercontent.com/61888437/236890958-e53eafd1-3380-40b6-b8e5-3f509da5d2d0.png)

![image](https://user-images.githubusercontent.com/61888437/236890997-c6cf999e-d0d5-4aa8-b21c-3e8c5e2b5d54.png)

**Comment by bi0hazard6** [comment]
![image](https://user-images.githubusercontent.com/33207067/236895529-bca1e242-ce15-4efb-ba89-6b04299d9d6c.png)
![image](https://user-images.githubusercontent.com/33207067/236895592-db889579-5895-4549-a13b-b60602927374.png)

**Comment by Lailloken** [comment]
Huh, that's interesting. Which language settings are you using in Windows (just out of curiosity)?

You can download this [dev-version](https://github.com/Lailloken/Lailloken-UI/archive/refs/heads/dev.zip) which should fix this issue. It also changes how the kill-tracker is started: instead of clicking the flashing timer, there will be a reminder-tooltip asking you to press the omni-key to activate the first /kills command.

There is no documentation of further changes at the moment, but I don't think there was anything major (it's been a while since I have worked on it because I suddenly lost interest in the league and took a break).

**Comment by bi0hazard6** [comment]
French (Canada).

**Comment by bi0hazard6** [comment]
Still 0 kills
![image](https://user-images.githubusercontent.com/33207067/236956549-ac009fbd-98da-4560-8072-c18e3dbae68c.png)

**Comment by Lailloken** [comment]
Then it's probably using a character as thousands separator that's not rendered in the chat-box.
I have updated the dev branch again, this time with a fix that should universally solve this issue.

**Comment by bi0hazard6** [comment]
Yup, it's fixed now. Got a nice drop with it too :)
![image](https://github.com/Lailloken/Lailloken-UI/assets/33207067/d8a885b7-d255-41a5-a813-77fc90619337)
