### ISSUE TITLE
Recalibrating "the pixel-check for the inventory" didn't solve the "Item-info vanish" problem

### ISSUE THREAD

**Issue by LuckyTianTian2** [Lailloken/Lailloken-UI#256]
The item info works fine in windowed mode, however, it vanished in windowed fullcreen mode, even if I recalibrated the pixel check for many times. I am running the game in 3840x2160.

One interesting thing I found is that if I do the following:
1. click calibration with item panel open, it shows "success".
2. click test, it sometimes shows "positive", sometimes shows "negative"
3. I continue to do the calibration until the test shows positive.
4. Then I hold middle mouse on an item, the item-info vanishs after a split-second.
5. After that, I re-click test, it shows "negative" again. 

Another interesting thing I found:
1. Click "restart as administrator" sometimes will show the following error:
![Snipaste_2023-07-29_01-46-16](https://github.com/Lailloken/Lailloken-UI/assets/140843177/4073dffe-0f16-4f01-8c45-fc5c6e700711)
2. If I click "Y", it goes to the main menu of the script.
3. If I click "N", the script closes.
4. However, If i didn't click anything and move the error window to the right-bottom corner to hide it, then I hold my middle-mouse on an item, the item info works without vanishing ! So wierd...  It seems there's a part of the script which caused the vanishing problem, and the item-info checking works for me if the script didn't run correctly. Although in this case, i will not be able to see the main menu and do any settings editing anymore.

Do you know how to fix this issue?
Before the problem is solved, I will play the game with the error window hided in the corner. 

Thanks a lot and sorry for my poor English.

**Comment by Lailloken** [comment]
Do you play at 2160p natively or are you using some form of upscaling? And are you maybe using graphical filters (e.g. via ReShade or Nvidia GFE)? Maybe AutoHDR in Windows?

It sounds like the script can't consistently get the right pixel-colors from screen. The error message from your screenshot is related to the version-check timing out because the GitHub servers took too long to respond.

I'm grabbing something for dinner right now, will look into the pixel-check afterwards.

**Comment by LuckyTianTian2** [comment]
> Do you play at 2160p natively or are you using some form of upscaling? And are you maybe using graphical filters (e.g. via ReShade or Nvidia GFE)? Maybe AutoHDR in Windows?
> 
> It sounds like the script can't consistently get the right pixel-colors from screen. The error message from your screenshot is related to the version-check timing out because the GitHub servers took too long to respond.
> 
> I'm grabbing something for dinner right now, will look into the pixel-check afterwards.

**Comment by LuckyTianTian2** [comment]
Problem solved. 
I can just press shift-F2 to disable Reshade temporarily and use item-info checking. 
After that, I press shift-F2 again to enable Reshade, and play the game again.

Thanks so much for the fast and super efficient solution !

**Comment by Lailloken** [comment]
As a temporary fix, you can open ini\screen checks (2160p).ini and delete the [inventory] section and the three lines underneath. It's a bit of an oversight that one cannot disable the inventory check, only recalibrate it. If there's no data stored, the script should ignore the state of the inventory.

Depending on how many features you're going to use that depend (or make use of) on screen-reading, you may run into more problems because of ReShade.

**Comment by LuckyTianTian2** [comment]
> As a temporary fix, you can open ini\screen checks (2160p).ini and delete the [inventory] section and the three lines underneath. It's a bit of an oversight that one cannot disable the inventory check, only recalibrate it. If there's no data stored, the script should ignore the state of the inventory. EDIT: restart the script after deleting the lines.
> 
> Depending on how many features you're going to use that depend on (or make use of) screen-reading, you may run into more problems because of ReShade.

It worked. I will see if it will cause any other problems and decide which method to use.
Thank you so much! I do appreciated.
