### ISSUE TITLE
Assigning the omni-key to a character key breaks vendor searches with leveling tracker

### ISSUE THREAD

**Issue by BeastgameTL** [Lailloken/Lailloken-UI#259]
Assigning the omni-key to a button that produces a character (like `.` in my example) breaks the gem buying regex, as it puts the character at least once in front of the string.

Example: `.^(Raise\sZ)` instead of `^(Raise\sZ)`

I don't remember having this problem in older releases. I am currently on v1.30.6 with the last working release being v1.30.2 (Although I could be wrong about this).

**Comment by Lailloken** [comment]
The regex used to be on ctrl-F, maybe that's why this didn't happen before (at least that's all I can think of right now). The official recommendation has always been not to bind the omni-key to a key that's used for chatting, but I wasn't actually thinking of this problem -- just that features might accidentally be activated while chatting.

I took it off ctrl-F to avoid clashes with macros or features from other tools. Changing it to be a short omni-press might fix it, but then again some people's short-press might still be long enough for the game to register the key being held down. So the recommendation to keep it off chat-keys is the only way to avoid it 100%, I think.

**Comment by BeastgameTL** [comment]
I don't see a use case where you would need the previous content of the search field followed by the regex. So maybe clearing it would work.

Something like: 
```
 SendInput, ^{f}
 sleep 100
 SendInput, ^{a}
 SendInput, {Delete}
 SendInput, ^{v}{Enter}
```

**Comment by BeastgameTL** [comment]
Either fix works, so I might as well close this. I originally changed the keybind, because my middle mouse button didn't work quite right and I was struggeling to find a comfortable, single, non-character key (Some combinations like `ctrl+space` also didn't work as keybinds).
