### ISSUE TITLE
Issues with contracts and blueprints in map tracker

### ISSUE THREAD

**Issue by worldendDominator** [Lailloken/Lailloken-UI#264]
![изображение](https://github.com/Lailloken/Lailloken-UI/assets/6707627/7cbb878d-9c96-4a37-a619-a549af3729a9)
Several issues here:
1) Area levels below 68 (lines with 1.0% e-exp on the image) are displayed as tier 1.
2) Kill counters don't work, even though I get the pop-up and update kill count every time I enter.
3) Mod tracking doesn't work either.
4) Not specific to the tracker, but "ffi" letter combo is replaced with a special ligature that's invisible in this font.

For point 1, I can suggest the way Exile Diary did it - write "L67" (or whatever the number is) instead of tier.

**Comment by Lailloken** [comment]
Okay, weird. Seems like I totally skipped heist when rebuilding and testing the tool, like if it didn't exist.

2. That was because, in my mind, the rogue harbor didn't exist as a hideout/town area
3. Similar to point 2: the maptracker and map-info features compare the entered area and the map loaded into the panel, and I totally forgot contracts/blueprints were a thing
4. I think the font causes issues on specific OS locale settings. I had very few reports in the past, I think from Russian users.

I don't know if I can get the update online today, though, I have some IRL stuff to take care of.

**Comment by worldendDominator** [comment]
Probably related, at one point I've noticed two map panels (those small ones that show current map name, tier, and timer) overlaid on top of each other.

**Comment by Lailloken** [comment]
Added the fixes and changes to v1.50.1, but the included updater was broken. You'll have to update manually to get the changes (and a fixed updater).
