### ISSUE TITLE
Write-permission warning when everything is ok

### ISSUE THREAD

**Issue by MrOne1676** [Lailloken/Lailloken-UI#266]
When i run script i got write-permission warning even everything is ok and:
- i run it as administrator
- in folder when everyting have permission to write
![image](https://github.com/Lailloken/Lailloken-UI/assets/98280063/734d52b8-1543-49a6-8642-9cd6c2cc46bd)

I do test from UI and got that result
![image](https://github.com/Lailloken/Lailloken-UI/assets/98280063/dc651bd0-c06e-41b2-930e-77fda9940e85)

**Comment by Lailloken** [comment]
Could you restart the script and then, when the error appears, double click the `L` icon in the system-tray and take a screenshot of the bottom of the AHK-log?

**Comment by Lailloken** [comment]
Apparently, it cannot create `img\Recognition (XXXXp)`. Could you double-check if that folder is really missing inside the img-folder? `XXXX` is your screen resolution, e.g. 1080

**Comment by MrOne1676** [comment]
There is only GUI folder.

Also download las release instead of copy github repository and same situationm here is folder tree
![image](https://github.com/Lailloken/Lailloken-UI/assets/98280063/572cfff8-351c-4b98-afab-427c13d75205)

**Comment by Lailloken** [comment]
There seem to be issues with creating folders deeper inside the folder structure. It had no problems creating the cheat-sheets, exports, ini, and update folders. But the write-test also creates files and folders inside data\write-test, so I don't really know why it cannot create the recognition folder.
You could try creating the `recognition (XXXXp)` folder inside img manually and see if it then can create folders inside it. Otherwise, you'll have to also manually create a `GUI` and `Betrayal` folder inside there. Another thing you could try is moving the folder outside of your C-drive.

**Comment by Lailloken** [comment]
> Maybe script cannot recognise my screen resolution because i have two monitor setup, and didnt make correct folder?

No, you can't get that far into the tool if it can't recognize your resolution (there are certain unsupported ones, so the check has to pass). The folder check happens basically at the very end. Maybe Windows doesn't like the folder name or sees a specific pattern and then blocks it.
Glad it worked out in the end. For the next version, I'll also include in the error-message which folders cannot be accessed/created so it'll be easier to report and get support.

**Comment by MrOne1676** [comment]
:) this is not the end of problems, i try to use Betrayal info i can open menu using mButton but it cannot recognise members when mouse over, like in wiki
![image](https://github.com/Lailloken/Lailloken-UI/assets/98280063/f17f1040-ee61-4d97-830f-7ae069c6147e)

![image](https://github.com/Lailloken/Lailloken-UI/assets/98280063/84a33a58-cfe4-472e-9775-49af8362be85)
