### ISSUE TITLE
Feedback: I prefer the 1.30 clone frames UI

### ISSUE THREAD

**Issue by Vadskye** [Lailloken/Lailloken-UI#271]
I've tried using both 1.30 and the new 1.50 beta, and right now I prefer 1.30. It has two important advantages:
* Being able to type the scale factor in directly makes it much easier to create multiple clone frames next to each other. (I wish I could also type in the x/y position!)
* New clone frames default to being active, which matches my expectation.

With that said, I prefer the way the clone frame box is displayed in 1.50, and it's more obvious how to delete or edit the clone frame. So they both have benefits! But overall, I prefer 1.30 right now.

**Comment by Lailloken** [comment]
Thanks for your feedback, very much appreciated.

**Comment by Lailloken** [comment]
I made some changes based on your and prior feedback:
![image](https://github.com/Lailloken/Lailloken-UI/assets/61888437/53891674-9eae-483c-b11a-a672a34e68f4)
- coordinates and values are fully exposed again

- fine-tuning has moved from up/down buttons to scrolling the wheel while hovering the corresponding edit-field
- snapping corners to the cursor-position is back to simple F-key presses because activating the corners and using arrow-keys felt a bit clunky and was hard to explain succinctly via tooltips

Let me know what you think and feel free to leave additional suggestions.

**Comment by Lailloken** [comment]
v1.50.2 now includes the changes mentioned above
