### ISSUE TITLE
1.50.1 game-window settings is bad

### ISSUE THREAD

**Issue by Domosed** [Lailloken/Lailloken-UI#277]
In Lailloken-UI-1.30.6 my windows always be in horizontal and vertical center of screen. now horizontal it's center but vertical it's top. 
Will be good if make addition setting for vertical position or window position offset for x and y.

**Comment by Domosed** [comment]
i make hot fix for my self
	yTarget := vars.monitor.y + (vars.monitor.h - h) / 2
	
and set  % yTarget instead vars.monitor.y

**Comment by Domosed** [comment]
and about leveling guide overlay, will be good up them little bit for fully visible exp bar.

**Comment by Domosed** [comment]
you can use the number-keys 1 to 0 to jump to specific image slots (1-10) does not work for me

**Comment by Lailloken** [comment]
> Will be good if make addition setting for vertical position or window position offset for x and y.

I can add that, sure.

> and about leveling guide overlay, will be good up them little bit for fully visible exp bar.

It's by design. The buttons have the same height as the bar and also have fixed transparency, so exp should always be visible. Making the overlay float above the exp-bar wastes unnecessary space and looks bad.
![image](https://github.com/Lailloken/Lailloken-UI/assets/61888437/b97b6682-f584-451c-829b-77fb4828d1b1)


> "you can use the number-keys 1 to 0 to jump to specific image slots (1-10)" does not work for me

I removed the hotkeys but forgot to remove it from the wiki.
