### ISSUE TITLE
Default location of skill book button to toggle leveling tracker UI overlaps said leveling tracker

### ISSUE THREAD

**Issue by dyfrgi** [Lailloken/Lailloken-UI#281]
When I click this button, in it's default position at the center of the screen, it sits on top of the leveling tracker. To get the full leveling tracker UI (including, most importantly, the arrows to manually control progression), I can toggle it on/off/on and it will be layered correctly. Or, easier, I can move it off to the side.

It would be better for onboarding to move its default position a bit to the right or left, or to a different side of the screen.

**Comment by Lailloken** [comment]
Thanks for your feedback.
It's the default position for every toggle-button and it's by design. If the user is following the wiki setup-guide for a feature, they'll know it's resizable and movable. If they don't, its obnoxious positioning and size will make them realize that it must be customizable.

I could try to find a half-decent default position, but there's a chance that tool XYZ also uses that position (because it's so good). Then the user might think there's an incompatibility issue between those two and might not try to fix it (because that default position is so good that it must be hard-coded). On the other hand, said half-decent default position may be suboptimal for many users, but they'll live with it because they don't know any better.

So the intention is to make sure the user finds out about the customizability either way, and that they find the best position for their personal setup from the get-go.

**Comment by dyfrgi** [comment]
Hm, I guess that makes sense. I feel like the leveling UI and the toggle for it are part of the same "section" of the UI, so it's still a bit weird to me to have different bits of the same function that conflict. It's like if the game were to have health and mana on top of each other by default and you have to customize the UI to change that.

Maybe there's some other way to make it obvious that it can be moved, such that rather than forcing discovery through making it inconvenient by default the onboarding flow could get people to discover that through just... noticing that it can be moved. This is one thing that Awakened Poe Trade gets right IMO, because it pops up extra UI when you open the configurator and at that point makes it clear that you can move things.

What about showing some extra frame around draggable elements while the settings page is open? It might lead to people thinking that they need to have the settings page open to move things, but discovering that they can always be dragged seems less important than just discovering that they can be dragged.

**Comment by Lailloken** [comment]
Again, thanks a lot for your feedback. Not saying I won't change anything, but here are some initial thoughts and context:

> It's like if the game were to have health and mana on top of each other by default and you have to customize the UI to change that.

Well, of course you'd have higher expectations from a (commercial) product. I don't see Lailloken UI as a product at all. It's just my personal collection of tweaks and "tinkerings", often inspired by community mockups/ideas. To return the favor, I put in settings menus, UI, and documentation to make it somewhat usable for third-party. When it comes to standards, I'd compare my project to those old-school mods or custom maps, where function stands above form.

> This is one thing that Awakened Poe Trade gets right

Not sure what the general consensus is, but I would also categorize it as a product (having such a grandiose name and all). In any case, it's competing in a highly-crowded space of tools that are quite integral to the game (some might say they carry trade league). To put it bluntly: "it better be that polished".

> so it's still a bit weird to me to have different bits of the same function that conflict

That's my specialty: laziness. The leveling tracker is the third or fourth feature (I lost count, some came and went) that uses this kind of toggle-button. When first implemented, I wanted their default position to be in the middle of the screen (for the sake of being obnoxious, as mentioned), but then decided to put them at the bottom. The leveling tracker just happened to end up in the same spot. Should I have changed the default position? Probably. Will the user just put it somewhere else entirely anyway? Also probably.

> the onboarding flow could get people to discover that through just... noticing that it can be moved

Since my project is so all over the place and has many features that are so different from one another (or from other tools), I put heavy emphasis on the wiki. Almost every menu section has links to a wiki page, and I expect users to at least skim through them before diving heads-first into features they want to use. So laziness strikes again: Customizability is already mentioned in the wiki, so not having it in the tool itself is not going to kill anyone.

> What about showing some extra frame around draggable elements while the settings page is open?

I just thought about slapping "drag me" onto the toggle-buttons for as long as they're in the default position. That's about as much effort as I am willing to put into it right now. Thoughts?

**Comment by Lailloken** [comment]
toggle-buttons are now located in the top-left corner of the client (same as LLK-UI panel) by default
