### ISSUE TITLE
More convenient skill buying

### ISSUE THREAD

**Issue by Oxleyjus** [Lailloken/Lailloken-UI#282]
When you reach a step in the guide, where you need to buy gems ("highlight: hold omni key"). It highlights all the needed gems in the build and you should scroll to get all the needed gems.

It would be more convenient, that it would highlight gems, which are just needed for this step.

For example (I deleted part in leveling tracker.ahk, so it doesnt show highlight: hold omni key", but it shows what gems to buy on this step):
![image](https://github.com/Lailloken/Lailloken-UI/assets/39136990/482e7683-b9a3-4a94-bb02-d12eac45cd84)

If it would work how I am showing in this example, it needs to highlight only Frost Bomb, Flame Wall, Orb of Storms and Steelskin.

**Comment by Lailloken** [comment]
The vendor highlights from within the guide do indeed work the way you're suggesting. I think you're somehow triggering the "Hideout Lilly" search-string. That's the one that includes every gem from the build.

I tried it with a build that only has many gems for Siosa, so feel free to send me your PoB code so that I can double-check that specific build as well.
