### ISSUE TITLE
Drought Bringer

### ISSUE THREAD

**Issue by faraddox** [Lailloken/Lailloken-UI#29]
Hi there! Thank you for this awesome utility! First time enjoying new league content with great UI :)
For some reason it shows that i have 3x Drought Bringer while i have only one. Checked others in my list, didn't found any other issues for me. I tried to remove settings and scan again, nothing changed.
https://i.imgur.com/jl4xvFS.png

**Comment by faraddox** [comment]
Actually it also doesn't show -weaver monsters (except chaosweaver) in list and burn recipes with them.
https://i.imgur.com/FNBvVCh.png

**Comment by Lailloken** [comment]
The tool saves your inventory into the config.ini. Could you check the list in the file and see if it shows three drought bringers there?

**Comment by faraddox** [comment]
Found it, sorry, just saw your answer :) Yep, there are three droughts. I'll check what saved wrong, give me few minutes (i'll add config string and screenshot too).

**Comment by faraddox** [comment]
1st one is correct. 2nd one is corpse detonator. 3rd is corpse detonator too. I could possibly missclick during scan, if they were starting with same letter, but they aren't :) So 100% not a missclick.

[PixelSearch]
fallback=0
color1=0x110F0C
color2=0x1B1812
resolution=1360x768
game-version=31710
[Settings]
favorite recipes=arakaali-touched,
Burn-number=10
[Archnemesis]
inventory=rejuvenating,opulent,mirror image,abberath-touched,flameweaver,toxic,sentinel,crystal-skinned,temporal bubble,empowered elements,effigy,invulnerable,soul eater,drought bringer,chaosweaver,berserker,frost strider,steel-infused,soul conduit,overcharged,magma barrier,drought bringer,berserker,invulnerable,shakari-touched,invulnerable,drought bringer,overcharged,bonebreaker,overcharged,overcharged,-empty-,hexer,crystal-skinned,heralding minions,gargantuan,empowering minions,berserker,gargantuan,flameweaver,brine king-touched,berserker,arcane buffer,toxic,mana siphoner,malediction,gargantuan,frost strider,trickster,mirror image,evocationist,evocationist,flameweaver,overcharged,rejuvenating,-empty-,empowered elements,solaris-touched,corpse detonator,toxic,malediction,mana siphoner,gargantuan,-empty-

https://i.imgur.com/8pVqefk.png

Checking one by one now all of them.

**Comment by faraddox** [comment]
https://i.imgur.com/ys6NTLO.png
i see no real difference here (img\Recognition\768p\Archnemesis)
Is img\Archnemesis Icons folder for scanned icons? I don't have either Drought bringer or Corpse detonator icons here.

**Comment by Lailloken** [comment]
Alright, big thanks for being so thorough. Looks like we have an amalgamation of worst-cases here. First, you're running 768p which unfortunately has rendering variance in the game itself (see known issues in the readme). Second, drought bringer and corpse detonator seem to be reskinned icons (at least the skulls themselves). And finally, it seems I was a bit too conservative in setting the image size for scans at that resolution (I had to make sure the in-game frames don't impact image recognition) and also set the scanner too loose.

There are two solutions to this problem that come to mind: You can set the image recognition to be a bit tighter (open the script file in an editor and search for two lines containing *50; change this value to something lower and test again; repeat until it works correctly). Or you can set your desktop resolution to 720p (which isn't terribly different from 768p if you set it to scale correctly on your monitor, i.e. with black bars on top and bottom, as when watching a movie).

The drawback of the first solution is that this might impact other icons and necessitate repeated specification, which in turn makes your database of scanned images larger and thus decreases scanning speed. The second solution has its drawback in having to switch back and forth between resolutions when you want to play PoE, and also starting scanner-training from scratch.

**Comment by faraddox** [comment]
I wont use other resolution anyways. Already not that big screen and i have some issues here and there because of this, especially with game visual clarity. I'll try first way and hope it works. Thank you very much for your help! :) You are very close to something that GGG should have done on their own before league release to make it pleasant and comfortable to play.

**Comment by faraddox** [comment]
Changed it to 25, scanned my inventory again. At least for now it detects each mod correctly. For now everything works fine, let's hope it stays fine later too :)

**Comment by Lailloken** [comment]
Glad it works for now. Please let me know if 25 works well in the long-run, so that I can patch it in officially.

**Comment by faraddox** [comment]
Didn't run too much maps yet (went to sleep yesterday after last reply). About 10 maps today. Didn't noticed any mistakes yet. But now it asks me sometimes to confirm mods which already were scanned earlier. Usually 1-2 mods per scan with almost full inventory.

**Comment by Lailloken** [comment]
Thanks for the feedback. I'm working on an optional workaround for resolutions that are not correctly supported by the game itself, i.e. those resolutions that render icons inconsistently (768p, 1024p, 1050p, and maybe more). Users running those resolutions will have the option to force the window into a specific height that is better supported and will lead to better and more consistent scan results. In your case, you could force the window to be 1360x720, which would only lose you 48 pixels' worth of screen height, but improve scanning significantly.

Slightly off-topic: In your first screenshots, there's the bug of "ff" not being displayed correctly (e igy instead of effigy) because of the custom font. This also probably happens in game when viewing advanced mod descriptions (su ix instead of suffix). This happens because you installed the font on your system, which you don't have to for my tool. The game somehow uses the font on the system if it's installed, instead of its own, and "ff" is bugged for some reason. So if you don't need the font for anything else and want to fix this bug, uninstall the font from your system.

**Comment by faraddox** [comment]
I'm not using any custom fonts for PoE, weird. I have missing double "f" in other tools for poe (trade companion for example), but not ingame - all descriptions are correct.

**Comment by Lailloken** [comment]
> I'm not using any custom fonts for PoE, weird.

I meant my tool using a custom font that is not usually installed on systems. I also mixed something up, now that I'm thinking about it. The "ff" bug occurred in game but not in the tool if the font was installed on the system, and you have it the other way around. I thought an old version of my tool -- when you had to install the font separately -- caused this, so I wanted to let you know, but that's irrelevant now since it doesn't affect your game tooltips.
It could be related to your system language settings, but I'm not sure since I also had the bug but in game instead.
