### ISSUE TITLE
Custom resolution problem

### ISSUE THREAD

**Issue by giurlaninick** [Lailloken/Lailloken-UI#294]
At the moment I'm trying to run with a custom resolution, which I'm aware is not entirely supported however I'm wondering if there is a workaround, since the pop-up on launch said something about being able to set it in as custom. However I'm only able to pick between 900 or 720.

Thanks mates

![image](https://github.com/Lailloken/Lailloken-UI/assets/50028437/8531c1f3-6780-4ea6-8b35-e6223b0ba78c)

**Comment by Lailloken** [comment]
No, there isn't. Vertical resolutions are limited to specific ones because the game itself behaves unpredictably at custom resolutions (or even standardized but less common ones, e.g. 768p).

By the way, if you're just starting to use my tool, I would highly recommend getting [the v1.50 beta](https://github.com/Lailloken/Lailloken-UI/tree/beta). It's much more up to date and has improved user-experience.
