### ISSUE TITLE
Missing map modifier

### ISSUE THREAD

**Issue by worldendDominator** [Lailloken/Lailloken-UI#295]
![изображение](https://github.com/Lailloken/Lailloken-UI/assets/6707627/ea9c35d4-2597-4f5d-a6f5-0db997f2e310)
"Kirac's" mod (quant to rarity) is ignored by the map info panel.

**Comment by Lailloken** [comment]
I left it out because it doesn't affect difficulty, but then forgot to exclude it from the summary at the bottom, so it's kind of in limbo right now. I also thought there's nothing to react to: there's no need to avoid it, and you wouldn't start crafting around it (or is that a thing?). I guess it could maybe prevent you from re-rolling a map whose quant would normally be too low to run (if you're strictly rolling for quant), but I don't know if the mod makes up for that. It also doesn't really fit into any category -- maybe `area` if anything.
Is it just something you noticed, or do you see any benefit (that I'm not seeing) in listing it in the panel?

**Comment by worldendDominator** [comment]
There is no particular benefit, I just thought it's weird that there's a single mod that's absent.
It's up to you if you want to include it or not.
