### ISSUE TITLE
Kill tracker doesn't always work

### ISSUE THREAD

**Issue by worldendDominator** [Lailloken/Lailloken-UI#298]
Kill tracker doesn't work for a map (the map tracker says 0 kills) if I don't update the counter after leaving the map. While this could be intentional, I think it's safe to use the count taken after entering next map - it's not like I'm going to kill anything in the hideout.

**Comment by Lailloken** [comment]
It's a good idea, but it creates a few vectors for bugs/oversights and potentially promotes bad habits, which negates the QoL improvements of this change.

Regarding bugs/oversights:
- right now, the mapping tracker simply works in parallel with the contents of the client.txt: whenever something map-related happens, it will know immediately and then makes the necessary changes (logging the run, clearing the stats, starting a new run)

- linking the previous map's "kill-count update" to the next map's "kill-count start" requires breaking this parallelism and waiting for user-input, during which unforeseen stuff can happen (I would have to implement additional checks for things that wouldn't happen if the tracker and client.txt worked in unison)

Regarding bad habits:
- the current method of updating the kill-count has to stay in either way because one wouldn't be able to log the count for the final map of the session otherwise

- if there are two methods of updating the kill-count, the user will always use the more convenient one and get used to ignoring the flashing panel
- it's very likely they'll develop a bad habit of also ignoring it before logging off after the final map of the session

I wouldn't mind working through the potential bugs/oversights if the proposed change were to replace the current method entirely. But adding a secondary method that comes with potential risks doesn't sound appealing at the moment. I could add an option to also display the reminder tooltip for updating the count via the omni-key, but that could be annoying depending on how much you trade during mapping.

**Comment by worldendDominator** [comment]
That's fair. I misunderstood the section of the wiki that said you don't have to manually finish tracking a map's (which is done through the same panel) unless you're going to do some untracked content. Thought kill counter update is optional as well.
