### ISSUE TITLE
Text misidentification in Heist

### ISSUE THREAD

**Issue by worldendDominator** [Lailloken/Lailloken-UI#302]
![изображение](https://github.com/Lailloken/Lailloken-UI/assets/6707627/0ae8ddf2-d422-43e9-b815-8d320a799d12)
![изображение](https://github.com/Lailloken/Lailloken-UI/assets/6707627/9a59e5ea-1e79-4109-be99-8db1aa8c9b69)
Map tracker showed that a contract run had an expedition encounter, which is obviously impossible.
Probably something in the chat log matched a line used in expedition, though I'm not sure.

**Comment by Lailloken** [comment]
Whoops, I messed up an exclusion rule for content-tracking. Thanks for reporting, I'll fix it for the next release.

**Comment by Lailloken** [comment]
Fixed in v1.50.7
I also made an undocumented change for your `ffi` issue: you can now place an alternative font-file into the `data` folder. Name it `alt_font`, then restart the script. However, it must not be a different font-type altogether: it has to be Fontin SmallCaps. I think using a different version of Fontin SmallCaps might fix the rendering issue.
