### ISSUE TITLE
[Bug] Leveling timer sometimes causes error when holding TAB

### ISSUE THREAD

**Issue by dsf3449** [Lailloken/Lailloken-UI#312]
LLK Version: 1.50.8
AHK Version: 1.1.37.01
OS: Windows 11

No solid repro steps on this one unfortunately, I just know that it happens _sometimes_ when holding tab while having an active campaign timer running. Possibly when tabbing back into the game from an external window? 

![image](https://github.com/Lailloken/Lailloken-UI/assets/25350725/e82c89cb-baef-40d7-b385-b8432d81400c)
![image](https://github.com/Lailloken/Lailloken-UI/assets/25350725/5bed106f-662b-4a0b-bb22-0bf481210c8c)

**Comment by Lailloken** [comment]
Thanks for reporting, I'll see if I can figure out what's happening.

**Comment by Lailloken** [comment]
v1.50.9 contains a potential fix for this problem (I couldn't replicate it on my end). I have renamed the thread to be more specific and to make it easier to find, just in case more people encounter the same problem. I'll leave it open for now, feel free to report back whenever you use the timer again in the future (next league, or during the next events).

**Comment by dsf3449** [comment]
@Lailloken Unfortunately, I ran into this issue again today. I have a "more consistent" repro of just spamming tab with varying degrees of delay, although it's still pretty inconsistent. This is a thing I do during leveling for some reason (constantly opening and closing the map), so I guess that's why it only shows up then.

I edited the `leveling tracker.ahk` to have a try catch around the problem code, here's what it shows:
So, first off there's a bunch of these which say "not initialized". I don't know if that is normal or not, just pasting it here anyways.
![image](https://github.com/Lailloken/Lailloken-UI/assets/25350725/88b3a385-a84f-4463-b35e-a20e5a231a63)

Then there's the exception object (among other variables):
![image](https://github.com/Lailloken/Lailloken-UI/assets/25350725/5f4fea84-4dca-4f5a-a0f4-9f2e9cc45366)

I don't know all that much about AHK but I'm assuming the gui name being referred to in the error is the value of `%leveltracker_timer%`, which in this case is `"0x7a08dc"`
![image](https://github.com/Lailloken/Lailloken-UI/assets/25350725/a1f59412-8a61-4e07-bade-763aae20147f)

I'm not seeing the value  `"0x7a08dc"` anywhere in the variable list, so maybe that's the issue?

I still have the script paused on the exception, so if there's anything else I can provide to help track the issue LMK!

This is the error I'm getting today, just for consistency:
![PathOfExileSteam_RVnMNVuRZW](https://github.com/Lailloken/Lailloken-UI/assets/25350725/fb43ed14-a795-4ecc-8721-3ba051d5327a)

**Comment by Lailloken** [comment]
Thanks for poking around and helping out with this issue (and I'm sorry you had to endure going through that mess).
I still cannot replicate this, even after spamming TAB like a mad-man and having my screen turn into a rave of flashing overlays.

> `%leveltracker_timer%`, which in this case is `"0x7a08dc"`

It's a local variable that stores the handle of the GUI, which in this case is `0x7a08dc`. It's stored there automatically when the new GUI is created in the line `Gui, New, % "-DPIScale +LastFound -Caption +AlwaysOnTop +ToolWindow +E0x02000000 +E0x00080000 HWNDleveltracker_timer"` (by means of using the `HWND` option).

So the weird thing is:
- the function creates the new GUI, seemingly successfully (otherwise the variable wouldn't contain a handle)

- the error-check I implemented last time doesn't return positive (it tries to get the position of the panel that says "act X" within the GUI in order to check whether the GUI was created properly, i.e. whether it even exists)
- the tool still cannot address the GUI to display it on screen ("invalid Gui name" basically means "a GUI with that name doesn't exist")

There have been a few reports of GUI-issues with similar patterns recently, and one commonality I noticed was that the script was located on the C: drive (see #324, where the tool can't use a handle to "attach" one GUI to another). Still inconclusive for now, I'm waiting for updates over there.

**Comment by dsf3449** [comment]
I'm going to disable the leveling timer for league start later, so don't stress about getting it fixed before then

**Comment by Lailloken** [comment]
I released a [test-version](https://github.com/Lailloken/Lailloken-UI/releases/tag/v1.51.3-test) for v1.51.3 yesterday that contains a fix for a different GUI-related issue. It's possible that these changes also fix the timer issues. Feel free to give it a try the next time you're using the leveling tracker.

**Comment by Lailloken** [comment]
I have re-integrated the timer into the main overlay (similar to how it was pre v1.50), so this particular issue should be resolved from now on.
