### ISSUE TITLE
[Feature requests]

### ISSUE THREAD

**Issue by Kazatel** [Lailloken/Lailloken-UI#313]
hi sir, 
I was with you when you started the project during Archnemesis league :D , need to say you move this to another level. Great job. 

requests:
for red -blue altars, make identification and suggestions and highlight for wanted and unwanted altars.

For expedition same thing, mark deadly/unwanted or wanted markers.

would be possible to do tracker for incubators how many you have and if you need to fill up some and on which item.
No issue if you use same level , but on the beginning if you mixing a lot , could be handy.

**Comment by Lailloken** [comment]
> I was with you when you started the project during Archnemesis league :D , need to say you move this to another level. Great job.

Thanks a lot.
***
> for red -blue altars, make identification and suggestions and highlight for wanted and unwanted altars.
> For expedition same thing, mark deadly/unwanted or wanted markers.

Someone suggested that before. The issue is that the background of the text-boxes is semi-transparent, which makes scanning/reading impossible with the current technique I'm using. The tool doesn't really _read_ text on screen, it simply compares saved image-files with what's on screen. The background will always be different (depending on location/map/effects), so recognition will probably never be precise enough.
![image](https://github.com/Lailloken/Lailloken-UI/assets/61888437/5d04b3e1-90d2-4c9c-8225-05a9c7d7af28)
***
> would be possible to do tracker for incubators how many you have and if you need to fill up some and on which item.

Generally it's possible, I guess, by using the /kills command. But it's impossible to fully automate that because of ToS. It would have to be a button (like notepad, leveling tracker, mapping tracker) that activates the /kills command and then shows which items still have incubators on them and which items don't.

**Comment by Kazatel** [comment]
Thank you for an update, new patch solved in some portion my request with incubators.
