### ISSUE TITLE
Active Image-Check won't return Positive.

### ISSUE THREAD

**Issue by SkaJump** [Lailloken/Lailloken-UI#315]
Specifically occuring with the skilltree overlay image-check. Checking the image folder for the .bmp, it was clipped as instructed.

Launched the .ahk with admin privileges, as well as with UI access (not concurrently) for the steam release of PoE, on 1440p resolution, on Windows 11
Clipped region as .jpg for github.
![skilltree](https://github.com/Lailloken/Lailloken-UI/assets/32431066/be7747f9-cae7-4d65-8508-a309dcfc4391)

**Comment by Lailloken** [comment]
The most common issue with screen-checks is graphical filters such as ReShade, Auto-HDR, Nvidia GFE, or adaptive sharpening.

If you're not using any of those, there's something else you could try. Ever since GGG deployed the engine/render update, a few people have reported issues with screen-checks under Windows 11 if the game is running with the DX11 or Vulkan renderer. Switching to DX12 seems to fix that most of the time.

**Comment by SkaJump** [comment]
Confirmed. Just switching to DX12 solved it. 
Thanks :)
