### ISSUE TITLE
Issue w/ search strings

### ISSUE THREAD

**Issue by tmckzs** [Lailloken/Lailloken-UI#319]
Hey, might be something I'm doing, but I am having trouble figuring it out.

Set search strings up per the example, but using stash for crafting purposes. Calibrate and test pass. Added search strings, made sure they're there. Omni key doesn't open any search strings when stash is open.

2560x1440, windowed full screen, running as admin.
![image](https://github.com/Lailloken/Lailloken-UI/assets/77239506/03b88297-4982-4b26-b154-4012f5fad6ae)
![image](https://github.com/Lailloken/Lailloken-UI/assets/77239506/9de22752-5507-4c09-94eb-79aa4ba430e4)
![image](https://github.com/Lailloken/Lailloken-UI/assets/77239506/80971e4c-ce55-4a3a-93f7-726db9b233c4)
![image](https://github.com/Lailloken/Lailloken-UI/assets/77239506/b192ce7e-1585-4487-9add-01d5d47139dc)

**Comment by Lailloken** [comment]
I just tested it, and it works for me when I calibrate it with the plaque at the top:
![image](https://github.com/Lailloken/Lailloken-UI/assets/61888437/2b7f416b-f1e2-43b6-bf47-e9c5645549a2)
***
![image](https://github.com/Lailloken/Lailloken-UI/assets/61888437/8402e861-491d-45ea-8725-d16d3751bddf)

**Comment by tmckzs** [comment]
Hey again, sorry for the late response - only play occasionally. So the omni key (default or anything else) doesn't open any search strings when the context menus are open (tried beast craft too). The calibration and test passes for both, but the string search never pops up when hitting the omni key. I'm using Vulkan renderer, not sure if that matters.


![image](https://github.com/Lailloken/Lailloken-UI/assets/77239506/f4d352a9-3e79-49ca-9af5-ccf73dde09e0)

**Comment by Lailloken** [comment]
Off the top of my head, there are two things you could try:

1. create a new search-string, calibrate it with Gwennen's gamble window, but don't add any actual regex-strings
![image](https://github.com/Lailloken/Lailloken-UI/assets/61888437/8e9627b3-f9dc-471d-8868-19ee20f559eb)

  - if you now omni-click while her window is open, a tooltip should appear
  ![image](https://github.com/Lailloken/Lailloken-UI/assets/61888437/3698ce27-7f54-4109-b279-08595206455d)

  - if that doesn't appear, try recalibrating the `gamescreen` pixel-check in the screen-checks section of the settings (the omni-key doesn't work correctly if that check is not calibrated, which may be the case here)
***
2. There have been a few reports of Vulkan and DX11 renderers causing problems under Windows 11, but in those cases the test after calibration wasn't even working, so I don't know if that is the problem in your case (since the test is working for you). You could try DX12 if the first solution doesn't work, just to test it.
