### ISSUE TITLE
[1.51.0] Leveling tracker progress meter / timer wont reset.

### ISSUE THREAD

**Issue by TechTrooper** [Lailloken/Lailloken-UI#328]
Leveling tracker progress meter / timer wont reset.
I've made several new characters, but the timer seems to be stuck with no way to reset it manually?

Also previous version had this same issue.

Can't find file named "campaign runs.csv" mentioned in instructions, would've tried deleting that.

![image](https://github.com/Lailloken/Lailloken-UI/assets/3955313/f5b1cd05-e94c-4509-b2d9-93f496e513e5)

![image](https://github.com/Lailloken/Lailloken-UI/assets/3955313/25c6f12b-f68f-45c2-9754-14688e9af842)

**Comment by nbrugger-tgm** [comment]
I think it should be resetable after leaving the twilight strand because if lailoken or the user messes up the tracker now cannot be reset without deleting content in the file. There is a RESET button in the settings (
![image](https://github.com/user-attachments/assets/82918cd5-54c2-4988-b960-058195585cd0)
) but it doesnt seem to reset timer and/or anything else
