### ISSUE TITLE
MAP-INFO Cannot read mod

### ISSUE THREAD

**Issue by FadeDeklin** [Lailloken/Lailloken-UI#341]
Is this some kind of bug? The version is 1.51.2
I don't know if there are some more mods it didn't read,
but I found this: "Players have 60% Non-Curse aura" is missing on the MAP-INFO
![Mapinfo](https://github.com/Lailloken/Lailloken-UI/assets/10823014/c2090f7c-2146-48b2-9d74-f6d79e66ce9c)

**Comment by Lailloken** [comment]
Yes, it's a recent bug. Thanks for reporting, it should be the only mod that doesn't work (it's because of the hyphen in "non-curse").

If it's an important mod for your builds, you can edit the `data\english\map-info.txt` file to fix it for now (there won't be any updates until after Christmas):
- search for `noncurse` in the file, place the hyphen, then save it

**Comment by Lailloken** [comment]
fixed in v1.52.0
