### ISSUE TITLE
Betrayal Overlay Not Showing

### ISSUE THREAD

**Issue by beagle1998** [Lailloken/Lailloken-UI#350]
I made sure screen check betrayal is calibrated and tested success. But pressing my middle mouse button(my omnikey setting) doesn't show the betrayal overlay. Maybe its because my screen is ultra wide? I'm not sure.

**Comment by Lailloken** [comment]
Some things to test:
- make sure the "game-screen" pixel-check is set up correctly
- make sure you're holding down the omni-key
- to test if the middle mouse-button is the issue, rebind the omni-key temporarily (e.g. F1) and check if that works

**Comment by beagle1998** [comment]
Thank you it was the game screen test. Also is there a way to toggle the betrayal overlay instead of holding omni key?

**Comment by Lailloken** [comment]
No, unfortunately there isn't. And I cannot easily change it because it's coded around being like that.

I made it behave this way because you normally just glance at it. If it says on screen "XYZ moves to Transportation", you hover over XYZ, hold the key, then either have them make the move or release them. That decision mostly doesn't take more than two seconds, so holding the key for that short period has less friction than having to press it twice.

Same if it says "X moves to Intervention, Y moves to Research": You hover over X, hold the key, quickly check what that movement would mean in terms of rewards, then move the mouse to Y and it will automatically loads their rewards since it continually scans while holding the key.
