### ISSUE TITLE
Screen-Checks Fail with HDR Enabled on Dell AW3423DW (v1.52.3)

### ISSUE THREAD

**Issue by Japper1** [Lailloken/Lailloken-UI#351]
When HDR (High Dynamic Range) is enabled on the Dell AW3423DW monitor, all screen-check functionalities fail to operate. Turning HDR off resolves the functionality issue, but results in significantly washed-out gameplay visuals, impacting the overall gaming experience. This issue is specific to HDR mode being active.

**Comment by Lailloken** [comment]
Ah right, my bad. I recently re-wrote the list of common issues / limitations and forgot about Auto-HDR and graphical filters because these issues are reported rather rarely.
I don't think there's a fix outside of disabling HDR. The issue usually stems from algorithms being dynamic, leading to the final screen-output looking different from one situation to another.

**Comment by Lailloken** [comment]
Actually, there is a potential fix in the future. I just implemented a feature based on OCR. If that turns out to run well, I am planning to add an optional alternative screen-check mode based on OCR.

**Comment by aasmall** [comment]
I have the same issue. Happy to hear there may be a potential fix. the OCR feature you just added appears to work, but I haven't yet tested it with an eldritch altar.

**Comment by lcbm** [comment]
Having the same issue w/ HDR enabled in the monitor in the image attached.

I disabled HDR, did the screen checks then re-enabled HDR. At least so far, the omni-key seems to be working as expected :) 

![image](https://github.com/Lailloken/Lailloken-UI/assets/31375047/382e25cf-62e6-4dc6-b4a9-903f8dabea53)

**Comment by Lailloken** [comment]
Before I start testing the alternative, OCR-based screen-check method on my end, could one of you do some testing for me **`with HDR enabled`**? I need you to do the following steps (not necessarily right now, I'm just posting now so I don't forget it later):

0. (skip if you have `not` activated/unlocked the TLDR-Tooltips or Necropolis feature yet): open the `ini\ocr.ini` file, change `allow ocr=1` to `allow ocr=0`. Then save the file and restart the tool.

1. open the character-stats screen in game (default: c-key)
2. open the settings menu by clicking the cogwheel in the main toolbar, then move it so it doesn't block the stats screen
3. go to ` TLDR-Tooltips `, the checkbox should be highlighted red
4. **`right-click`** the checkbox, and the Windows Snipping Tool will open
5. screen-cap a few lines from the lower half of the character-stats screen, and a new window with said screen-cap and the OCR-result will open
6. take a screenshot of that window and attach it to a reply in this thread

I want to know what screen-caps look like with HDR enabled, and whether or not it influences the OCR-result.

**Comment by aasmall** [comment]
![image](https://github.com/Lailloken/Lailloken-UI/assets/4071702/528fa118-826f-43ef-a4e3-bf9b073cce4c)

**Comment by aasmall** [comment]
oh, ya, it looks very strange in that ui
![image](https://github.com/Lailloken/Lailloken-UI/assets/4071702/6ad5b670-a898-4f5f-9dee-4ba551c5158c)

**Comment by Lailloken** [comment]
I was wondering if the screen-checks are failing because of those differences between the two screen-caps. It looks as if the Snipping Tool is capping the screen before HDR is applied, whereas the tool itself caps it after the fact. (I don't know how system-level HDR works, so I'm just spitballing).

[Here](https://github.com/Lailloken/Lailloken-UI/blob/dev/modules/screen-checks.ahk) is a modified version of the ` screen-checks.ahk ` file (there's a download button near the top-right):
![image](https://github.com/Lailloken/Lailloken-UI/assets/61888437/5878666f-dadd-4591-a9e8-cd233cd0a3bd)

Download it, rename your current ` modules\screen-checks.ahk ` file, paste the new file into the folder, and restart the tool. This modified version changes the process after clicking the ` cal ` button of an image-check. The Snipping Tool will still launch (just to make use of its freeze-frame), but the screen-cap is taken internally. Does that change anything when testing image-checks afterwards?

**Comment by aasmall** [comment]
mostly works, some odd behavior which seems mostly around detecting when the snipping tool is done/window gone. It happened a lot more frequently before I turned off notifications for the snipping tool. It seemed like after I took the snip, AHK thought I was still in the snipping tool. It never returned me to your UI. I would have to restart the script. Disabling notifications helped, but not 100% of the time.
![image](https://github.com/Lailloken/Lailloken-UI/assets/4071702/8bcaa087-d392-441e-8216-8585c85cc3b6)

After disabling notifications, I was able to calibrate and test successfully with HDR enabled.

**Comment by Lailloken** [comment]
@aasmall Thanks again. The Snipping Tool has been annoying me for quite some time now, so I'll have to create my own solution in order to have full control and eliminate inconsistent behavior.

So my hunch was correct then. I'll make the necessary changes and update the test build as soon as possible. Unfortunately, I can't replicate the issue on my end (Win 10 lets me enable system-level HDR because my monitor has basic HDR capabilities, but it doesn't impact screen-checks), so I'll have to check back with one of you in this thread on a step-by-step basis.
(If any of you are using Discord, feel free to add me there to speed up feedback-cycles: lailloken)

**Comment by Lailloken** [comment]
[v1.52.6](https://github.com/Lailloken/Lailloken-UI/releases/tag/v1.52.6) now includes a custom snipping tool that correctly screen-caps HDR output. I'll keep this thread open for a while so potential new issues can be reported.
