### ISSUE TITLE
Archnemesis window closing on Scan

### ISSUE THREAD

**Issue by iamkhav** [Lailloken/Lailloken-UI#36]
When I click the Scan button in the Archnemesis window, the Archnemesis window closes before actually starting image recognition.
Subsequently, it does not recognize the first component (top left) since the Archnemesis window is closed.

After looking into the main script (Lailoken UI.ahk) I saw that there is an Escape-button send in line 1259 that causes this behaviour.
I'm not sure what exactly this send is supposed to do.
Line 1259: SendInput, ^{f}{ESC}

Reopening the window does not remove filters or search queries (which in my trials seem to throw off the image recognition).
Also there isn't really a command to reopen said window.

Commenting line 1259 out solved the problem for me.
Thank you for this great tool!

**Comment by Lailloken** [comment]
Yes, the ESC-input is there to clear the in-game search, just in case it's not blank. It seems ctrl-F is not sent in your case, which should also cause problems when clicking a recipe from the ready-list. I've not heard of partial send issues like this yet -- usually sent key-presses either fully work or they don't. What happens when you click an item from the ready-list?

**Comment by iamkhav** [comment]
Oh, I see. Sorry, I'm not well versed in AHK.
So ^f is a ctrl+f send.

Then I am pretty sure the problem is caused by the delay I experience when pressing ctrl+f in PoE. It takes approximately one second for the button combination to take effect. Therefore the Escape-button send simply cancels out of the window before the search bar is highlighted. 

This delay is a PoE specific problem that I do not experience anywhere else. 
However, seeing that I can't really find any other reports of this specific problem, this must be a very rare or individual case (.. and also not this releases problem). 

Not at the computer right now, will record a video later if that is of interest at all.

**Comment by Lailloken** [comment]
I see, that makes sense. I could fix that by sending ctrl+f on clicking the mouse button and ESC (for scans) or ctrl+v (for the other instances that use the search bar) on release. This way, you could time it and work around your delay issue. How would that work out for you?

**Comment by iamkhav** [comment]
It feels more appropriate for me to spend some time on trying to fix this problem at the root before making you program a workaround :D
Wouldn't feel right.

Besides, the delay is really annoying anyway. Must have made me cancel out of windows hundreds of times by now. To be honest, I didn't know people could instantly type after ctrl+f.

I will keep you updated.

**Comment by Lailloken** [comment]
All it takes is one extra line and one modified line, times three. I'll include it in the next release because it doesn't change a thing for regular use. This way, you can use my tool for the time being in case your troubleshooting takes longer than expected. The only thing you wouldn't be able to do is highlight assembled versions of prio-recipes -- you would have to search for them manually -- when they're highlighted in green.

**Comment by iamkhav** [comment]
I have found the problem introducing the delay. 
I am ashamed to admit that it's my trusty companion, the trade tool Sidekick.

The problem is that it captures the ctrl+f input for a functionality I do not even use. Some kind of internal search it seems.
Turning this functionality off in its settings has removed the delay.

I've been playing PoE with Sidekick for so long, I didn't even remember how things were before.
If there are any future PoE projects planned, we could talk about collaboration. Discord: Amon#5118
Thank you for your time and help.
