### ISSUE TITLE
Ctrl clicking items into my inventory hits the C key, even though I have set the config option about having it rebound.

### ISSUE THREAD

**Issue by sclient** [Lailloken/Lailloken-UI#365]
Have the option on 'the c key is used for something other than your character screen', but my aura that is bound to c turns on or off as the subject says. 

Not sure why it would be using the c key for ctrl clicking items into my inventory, but it seems to be.

**Comment by Lailloken** [comment]
You're using the loot-tracker feature within the mapping tracker, right?

The issue you're having is due to an in-game bug / weird behavior:
- pressing CTRL-C on an item to copy its data into clipboard works as expected

- pressing CTRL-C while there isn't any item underneath the cursor will trigger whatever is bound to the C-key (**`unless it's the default character-stats screen`**)

The option 'the c key is used for something other than your character screen' is only there to split the omni-key into two separate ones so that the above behavior doesn't happen every time the main omni-key is pressed.

So you'll either have to click slower when stashing items (or avoid clicking empty spots), disable loot-tracking, or bind the C-key to the character-stats screen again and use a different one for your aura.

If you're not using the loot-tracker, let me know (though I'd be at a loss as to what is causing this issue).

**Comment by sclient** [comment]
OK, I get that. I think Im going to move to exilence CE to track my loot instead. I never really check out what Ive gotten with Lai anyhow, so there isnt much reason to track it.

Thanks!
