### ISSUE TITLE
Black screen with custom snipping tool

### ISSUE THREAD

**Issue by RedBlueDevil212** [Lailloken/Lailloken-UI#368]
I tried to use the custom snipping tool for betrayal, but when + right click + middle mouse click, the screen turns black with instructions on how to use the new snipping tool. If you need photos, I can provide them.

**Comment by Lailloken** [comment]
Are you running Windows 11? I'm asking because there's a bug with Win 11 and DX11/Vulkan where the client often flashes black when the tool takes a screen shot. You can test it by opening the `screen-checks` section of the settings and spam-clicking `test` for the betrayal image-check.
Switching to DX12 in game usually fixes that.

**Comment by RedBlueDevil212** [comment]
Yes, im running windows 11 and im using DX11. I tested the spam-clicking and yes, it does flash black.

DX12 fixed it, thank you.
