### ISSUE TITLE
Necropolis calibration not flexible enough

### ISSUE THREAD

**Issue by EmmettJayhart** [Lailloken/Lailloken-UI#369]
When the Lantern menu is calibrated, it will only work for that specific number of enemy types.

If there is an increase or decrease in the number of enemy types, the positions of the enter button and the title bar will move to make or reduce space.

You can tell from these screenshots that the position changes, and as such the overlay doesn't work; I get the error "Couldn't find the \<Enter\> button on screen"

![Less mobs](https://github.com/Lailloken/Lailloken-UI/assets/23242564/3944f373-21ed-44ff-aab0-57df3c702036)
![More mobs](https://github.com/Lailloken/Lailloken-UI/assets/23242564/0180011b-7cf7-475d-bc34-78ee4ad93b62)

**Comment by Lailloken** [comment]
Thanks for your feedback. The in-game UI seems to be all over the place, I've had nothing but problems with it.

I noticed that the text in the plaque at the top shifts around depending on how long the mod-list is, so I changed that screen-check. Now it seems that this is also the case for the enter button at the bottom. I took your screenshots, cropped out the buttons and fed them into a comparison tool:
![image](https://github.com/Lailloken/Lailloken-UI/assets/61888437/53b8b528-700f-4ee9-a2b6-138852fb09d8)

The pink pixels highlight differences between the two images, which indicates that the text doesn't render consistently (which is why the tool can't find it). Looks like I have to find a way around that as well.

While we're on the topic of the necropolis feature: How does text recognition perform in general? I'm collecting feedback to see if it's viable to also use OCR in different aspects of the tool.

**Comment by Lailloken** [comment]
I have changed how the overlay measures the in-game UI for [v1.52.6 (Hotfix 2)](https://github.com/Lailloken/Lailloken-UI/releases/tag/v1.52.6). I have used it for around an hour and it seemed to work fine.

**Comment by EmmettJayhart** [comment]
I've been using the hotfix and it seems to be working, and not just that but I also don't need to manipulate the overlay offsets anymore; I reset them to default.

I haven't noticed any issues with the text recognition, I think my biggest problem is when I open the skill tree and it won't let me use that feature until I open my inventory. Although I think that might actually be the pixel-check thinking I'm still in the gamescreen so it may not even be about text recognition.

I also haven't been able to use the betrayal feature yet as I haven't done that much, but the necropolis OCR has been working for me.
