### ISSUE TITLE
Pressing the '-' '+' button will multiply launch the process

### ISSUE THREAD

**Issue by ysalpha2021** [Lailloken/Lailloken-UI#38]
Every time I click the '-' '+' button to change the font size, the process is duplicated.
By the way, when I right-click on the tasktray icon and 'Reload This Script', it reloads without any problem.
(Perhaps I am the only one experiencing this problem...?)

![DuplicatedProcess](https://user-images.githubusercontent.com/95667621/156690168-7d43a122-f5c5-409f-a9ec-3bafdb5392b4.png)

It is not a critical problem because if I restart the system, the font size will be displayed as I want it to be.

OS:Windows10 64bit
Lailloken-UI v1.21.2
Authotkey Version is 'v1.1.33.10 - August 29, 2021'

**Comment by Lailloken** [comment]
Seems to be an AutoHotkey bug, happened to me with other scripts in the past. I'll put in extra steps to kill the script instance since the script doesn't do it well by itself (it should be forced to only allow one running instance, and it should properly kill the running instance before restarting to apply size changes).
