### ISSUE TITLE
Issue with Necropolis overlay

### ISSUE THREAD

**Issue by malkz-br** [Lailloken/Lailloken-UI#382]
I managed to setup the overlay on the screen-checks section and the tests work well, but when I activate the necropolis mode the overlay just doesn't work.
When I try to change settings on the Necropolis section it gives me a message to "open the overlay before changing settings" regardless of the Necropolis panel being on the screen
Is there anything I am doing wrong?

**Comment by malkz-br** [comment]
![image](https://github.com/Lailloken/Lailloken-UI/assets/76183144/983a419f-33ed-4274-897c-98223d45b429)
Screenshot for reference

**Comment by Lailloken** [comment]
The "overlay" and the in-game panel are two different things. You generally open the in-game panel, tap the omni-key (default: middle mouse-button), and then the "overlay" opens.

**Comment by malkz-br** [comment]
Hey, thanks for the quick reply and for making this amazing tool available. 
I am aware of the overlay being a separate thing but in this case I can't make it work while the lantern menu is on the screen. I have already tried to rebind the omni-key but the overlay just doesn't work even though I do get a positive response on the calibration/test. 
Other functions such as the item tooltip also work just fine when I press the omni-key

**Comment by Lailloken** [comment]
Then it's probably the `gamescreen` pixel-check. Make sure you close every in-game UI, set the minimap to centered/overlay mode, then recalibrate the pixel-check.

The omni-key isn't searching for the lantern UI because it "thinks" you're on the gamescreen, controlling your character, so it doesn't even attempt to activate the necropolis feature.

**Comment by malkz-br** [comment]
I tried to recalibrate the gamescreen check but I still get the same issue. 
When I test the active pixel-check while the lantern menu is open I get negative as a result, while the lantern test is positive. If I close the lantern menu and do the same thing I get both the other way around.
Weird thing is that I was able to set up the TLDR overlay just fine

**Comment by Lailloken** [comment]
Hmm, I guess we have to test if different features where the omni-key works exactly the same, so `gamescreen pixel-check` -> `feature image-check` -> `activate feature`. That would be Betrayal-Info and the skilltree overlay in the leveling tracker.

Could you enable the leveling tracker, set up the `skilltree` image-check, then hold the omni-key while the skilltree is open? There will be an error message saying that image-files could not be found (or, if you have used that feature before, the overlay will open).

Other than that, what is your screen-setup? Do you use multiple monitors? What's the game's resolution, and is it running in windowed fullscreen or a different configuration?

**Comment by Lailloken** [comment]
There's a slight possibility that the tool can't correctly tell how/why the omni-key is pressed.

1. One thing that could be the issue is the clipboard. Could you copy a random word/text into clipboard, tab back into the game, press the omni-key `while not hovering over an item`, then paste the clipboard somewhere? I need to know if the clipboard is blank after pressing the omni-key. If it's not blank, the tool thinks you're pressing the omni-key on items every time.

2. Have you changed anything in the tool's `hotkey` section? You mentioned that you had rebound the omni-key.

3. Another thing you could try is this: There is a work-around for people who have rebound the c-key in game. They need to "create" a secondary omni-key for item-related features. It's an option in the `hotkeys` section (can't check right now what it's called, something with c-key and character screen). For testing purposes, you can bind the secondary omni-key to an F-Key. We need to check if removing item-related checks from the original omni-key fixes your issue.

**Comment by malkz-br** [comment]
I can't explain how, but it is working now
I tried to reconfigure everything before I read your last message, so I didn`t try any of your latest suggestions. 
What I did do was the following: I restarted everything, set a new omni-key, recalibrated the pixel check and the lantern check, etc), almost like a fresh new setup.
My guess is that  there was an issue with the omni-key I was using before. I noticed there was something weird with the one I was using when I was setting up the TLDR function. I accidentally pressed the omni-key while I was setting up the hotkey for TLDR and noticed that the input from pressing the omni-key was actually 2 characters (the input was showing up as something like " -© " instead of just " - "). I don't understand why this was happening but the important thing is that it is working now
I would like to thank you very much for your support. If you have any link for donations please share with me because I would like to express my gratitude with a tip (wont be much because my currency is worth nothing, but some is better than none I guess). I looke

**Comment by Lailloken** [comment]
I'm glad this issue could be resolved.
I'm currently not taking donations, but that may change in the future. I certainly appreciate the gesture very much.

Just keep using my tool if you find it helpful and recommend it to others if you think it might help them. Maybe there will be a donation button within the tool or on the GitHub page in the future, so you can tip me then if you still feel like it.
