### ISSUE TITLE
[Suggestion] Profiles for map mod highlighting

### ISSUE THREAD

**Issue by worldendDominator** [Lailloken/Lailloken-UI#384]
Let us save multiple sets of map mod highlights for different characters. There's already a similar feature for item mods, after all.

**Comment by Lailloken** [comment]
Hmm, I thought about it in the past and decided against it, but we can certainly discuss it. I don't remember every reason against it, but here are a few:
- the structure I used for saving the config would need to be revamped to allow for profiles, and the current config would have to be converted through an update (not a big deal, I would just have to get over my laziness)

- it feels like almost 75% of map mods would have the same tiering/highlighting across all of the profiles anyway (area mods, monster-type mods, etc.)
  - feel free to provide exceptions, I'm sure some mods are escaping my mind right now
- I thought there's only a hand-full of mods that can completely brick a map for certain builds
  - the intention was to mark them as tier/difficulty 4 for all builds, then use the cross-out feature to mark them safe/unsafe for individual builds

  - I recently added a mod-search to the settings to facilitate changing brick-mods in bulk, in case the T4/cross-out system was not preferred

While writing this, I had an alternative idea: I could add a section to the settings menu with "pinned" map-mods whose tiering/highlighting can be changed on the fly. The obvious default ones would be reflect, no regen, no leech, stun-immune, etc., and I would add a button to the results in the search-box so that the user can pin additional mods. That would get around the issue of that ~75% mod-pool that's the same across all profiles.

Let me know what you think.

**Comment by worldendDominator** [comment]
I wasn't aware of the mod search feature. It looks rather useful for this. But the idea of a settings section sounds even better since the mods are immediately in front of you and you don't have to remember which ones you need.

**Comment by Lailloken** [comment]
Here's how it turned out for now, and I'm pretty happy with it.

These five mods are pinned by default:
![image](https://github.com/Lailloken/Lailloken-UI/assets/61888437/3c2e6d2b-5cd3-41a9-a16a-ff68041b44a1)

And when you search for something, it looks like this:
![image](https://github.com/Lailloken/Lailloken-UI/assets/61888437/ad2eb763-4dd3-4afe-a63f-93131a0159ac)

Unless there's more you want included, this will be added to the next release.

**Comment by worldendDominator** [comment]
Looking good!

**Comment by Lailloken** [comment]
[v1.53.3](https://github.com/Lailloken/Lailloken-UI/releases/tag/v1.53.3) is now online. You can close this thread once you've tested the additions and feel everything's working as it should.
Thanks for the suggestion.
