### ISSUE TITLE
Omnikey triggering Stash-Ninja on rare amulets with scarab in name

### ISSUE THREAD

**Issue by MadMarbleHead** [Lailloken/Lailloken-UI#385]
The title mostly sums it up. When the omnikey is long-pressed over an amulet with scarab in the name, stash-ninja is triggered instead of Item-Info.

This occurs in 1.53.2 on uninfluenced, single influenced, and double influenced rare amulets in stash tab, quad stash tabs, premium stash tab center slots, in inventory, and while equipped.
![image](https://github.com/Lailloken/Lailloken-UI/assets/170190745/08bd68f5-1154-4e32-a12e-0e54e37013ff)
![image](https://github.com/Lailloken/Lailloken-UI/assets/170190745/ca1b20af-f841-4383-a39b-db08366f3f1b)
![image](https://github.com/Lailloken/Lailloken-UI/assets/170190745/ad1c1525-f52d-447a-99e5-5ec6cc231277)
![image](https://github.com/Lailloken/Lailloken-UI/assets/170190745/6db0dbbe-9522-43ab-bdb8-52939e46016b)
![image](https://github.com/Lailloken/Lailloken-UI/assets/170190745/16b14a2d-548d-4374-99ea-70a2dd81b297)

Item info is invoked (and does not function) correctly on Skittering Incubators and divination cards with scarab in the item description, both in stash and inventory.
![image](https://github.com/Lailloken/Lailloken-UI/assets/170190745/bd04f2d6-ca1f-4b6b-affb-5f8495713dd3)
![image](https://github.com/Lailloken/Lailloken-UI/assets/170190745/01ad7efe-9df4-4937-ab57-ca833f84ea02)

Amulets appear to be the only rare items with scarab in the name, so it appears to a non-issue on other item types.

**Comment by Lailloken** [comment]
Thanks for your thorough reporting, very much appreciated.
Since the live-version only supports the scarab tab, I went with the lazy/placeholder route when I coded the activation of the feature. I did check the trade-site beforehand to see whether names with "scarab" can be generated, but I couldn't find anything. I should've checked my own stash because I do have an amulet with "scarab" in its name.

My local dev-version already supports the "general" and "breach" sub-tabs within the fragment tab, so the omni-key activation has been changed accordingly. I can create a hotfix release that includes that.

**Comment by MadMarbleHead** [comment]
Glad to hear it! I'm absolutely in love with this tool and am excited to see it continue to grow.

**Comment by Lailloken** [comment]
Should be fixed in v1.53.2 (Hotfix 1).

**Comment by MadMarbleHead** [comment]
I downloaded and tested it, it's working on my end.
