### ISSUE TITLE
support more lng.

### ISSUE THREAD

**Issue by Devimax** [Lailloken/Lailloken-UI#387]
I propose to add the ability to adapt to other clients and interface languages ​​by placing “strings” in a separate file. For example, eu.lng de.lng and others. this will help connect the community to translation into other languages.

**Comment by Lailloken** [comment]
Well, today is your lucky day: [LINK](https://github.com/Lailloken/Lailloken-UI/discussions/categories/translations-localization)

The hosted files are not fully up-to-date because no-one has advertized/posted any plans of starting a translation project. I can push an update shortly in case you want to look into it.
