### ISSUE TITLE
click on the Available burn mods to highlight all burnable mods

### ISSUE THREAD

**Issue by FanghanHu** [Lailloken/Lailloken-UI#39]
as title, thank you for this amazing tool.

**Comment by Lailloken** [comment]
Sounds good. I would have to put in some kind of limitation, though, because the length of the burn list is so variable and the in-game search maxes out at about 50 characters -- some mod names also require longer search strings for proper distinction (X-weaver vs. X-strider, empowering minions vs. empowered elements). So I have to think about which criterion decides what goes into the search string in case it runs into the character limit (highest quantity or 'lowest' relative power ranking) to prevent it from being arbitrary.

Since this feature would mainly be used for blindly burning mods, I'd make it highlight the mods with the highest quantity at a given moment and simply put as many as possible into the string. I could also use this opportunity of quantifying burn mods to implement sorting the list by quantity or by relative ranking.

Thanks for your suggestion.
