### ISSUE TITLE
GeForceNow - UI Not Starting

### ISSUE THREAD

**Issue by Zezalee** [Lailloken/Lailloken-UI#392]
Hey, 

Wanted to test out the UI but when trying to get it to work with GeForceNow it never starts. No interface is ever created. Furthest I get is the AHK script starting and then closing itself again after the time-out period expires.

Additionaly, unsure if the [Awakened PoE Trade bridge for GeForceNow](https://github.com/KloppstockBw/GFNPoEPriceCheck) will affect the UI as it renames the GeForceNow window to "Path of Exile" rather than "Path of Exile on GeForce Now". However, regardless of this program running or not the above issue is still present.

**Comment by Lailloken** [comment]
I temporarily took out GFN support with v1.53.4 because I need to re-evaluate general compatibility.
I added very basic GFN support in the distant past due to requests but never really received good feedback. Now Stash-Ninja seems to be something GFN users are interested in, so this is the first time in a long while that people start testing the tool with GFN again -- and of course a lot is broken because it's been so long since general compatibility received any maintenance.

Only very recently did I start looking into GFN compat personally, and there's a lot that needs fixing and/or is generally incompatible. For example, GFN records mouse-clicks in a way that creates annoying issues with my tool: If the GFN window is active/focused and you click a different window, it sends that particular mouse-click to the game even if it was meant for the other window. As far as I can tell, while GFN is focused, it sends every single click inside the client-area to the game `regardless of whether or not it's actually meant for the game`.

**Comment by Lailloken** [comment]
I had some unexpected free time today and managed to give the tool a first, superficial GFN makeover. You can get that version [here](https://github.com/Lailloken/Lailloken-UI/archive/refs/heads/GeforceNow-testing.zip)

I fixed the window-mode issue and disabled features that are (currently) not compatible with GFN. I also modified the Stash-Ninja feature because it requires a new hotkey (since GFN doesn't have proper clipboard functionality -- the bridge would also be too slow). It's bound to F2 by default and will open a selection menu from which to pick a tab:
![image](https://github.com/Lailloken/Lailloken-UI/assets/61888437/06382c7b-d7e2-44e4-9318-ce8f4ad8dfc0)

Clicking an entry on the list will open the overlay for that type of tab.

**Comment by Lailloken** [comment]
The tool makes use of [screen-checks](https://github.com/Lailloken/Lailloken-UI/wiki/Screen-checks) (wiki-link in case you want to read more), which enables it to automatically toggle overlays if they would otherwise block something in game. Clone-frames make use of that: they hide when you open the atlas, then reappear when you close it again.

Those screen-checks have to be calibrated in the `screen-checks` section of the settings menu. Or you can turn that behavior off by unchecking the top checkbox in the `clone-frames` settings. I had to add additional adjustment-settings for GFN in the screen-checks menu (the help tooltips should cover everything).

**Comment by Lailloken** [comment]
The GeForce Now compatibility changes are now live in [v1.53.5](https://github.com/Lailloken/Lailloken-UI/releases/tag/v1.53.5). You can use the built-in updater to get that version and keep your settings from the test-version.
