### ISSUE TITLE
feature request - setting # of times I want to complete priority recipes

### ISSUE THREAD

**Issue by Esord** [Lailloken/Lailloken-UI#4]
In case you don't have anything better to do 🤣 

I got my priority recipes, but only really care to have X of each (either globally or preferably individually set-able (clicking on the recipe in the UI puts +1, right-click -1?)), after which I can remove em.

Let's put Inno-Brine-Treant-Tuko to priority. Currently everytime I can make any of these or the sub-recipes, it'll show as a priority. That's great, but there be bottlenecks. I make my X sets of Mana Siphoner/Drought Bringer, but then I don't really care about these cause I'm waiting to finish Sol/Lun, and don't wanna highlight those recipes anymore.
This can be circumvented by not using Inno-touched, but individual parts/subparts, but becomes annoying/impossible if I'm juggling more recipes :)

Or say I have X = 2. I make Brine/Treant/Tuko ahead of time, and am just waiting til I can finish my Inno. Now I'm in the process of making a spare set of these 3 ^. I finish Heralding Minions (BK), they don't show up as a prio anymore. Finish Ice Prison (BK), no more prio. Finish Storm Strider (BK), make BK#2, I can take it off prio, but in the process of creating another the materials can get used for w/e instead :)

Now a sub-request to this: a way to highlight what basic materials I'm missing to finish all my prioritised recipes (minus my inventory ofc, or perhaps just list a total # of each basic material that gets used in your prio recipes? or a highlight for basic ingredients that you need a lot of) (times X if implementing ^^)

**Comment by Lailloken** [comment]
1. Yes, the plan is to stop suggesting sub-components after you have finished them, so that their components can go to other parts of  prio-recipes. I don't know from the top of my head if I can implement the X sets option. But I definitely intend the tool to suggest the fastest road to complete the whole prio-list. I was half hoping the drop rates would balance that out and half just procrastinating :D. I thought the former was the case because nobody has mentioned it until now.

2. Do you mean like a kind of shopping list of remaining tier 1 mods to complete the whole prio list? For example: 4x overcharged, 3x incendiary, 2x bombardier (these are random numbers). That would be doable.
