### ISSUE TITLE
Long omni-key press don't work

### ISSUE THREAD

**Issue by yoporla** [Lailloken/Lailloken-UI#416]
All features bound to a long omni-key press don't work.
I think what it does is when I long press on the omni-key it instead press the omni-key many times (the wiki shortcut keep popping over and over)

any suggestions?

**Comment by Lailloken** [comment]
It may have something to do with how your mouse handles the key-press. Some mice have "features" that repeatedly send a key-press if you're holding that key down.

Check if you can disable that in your mouse software. If you're not using a special kind of mouse, maybe the key is just broken or semi-defective.

Have you tried rebinding the omni-key to a different key? But be careful: don't bind it to a key that is used for chatting, as you may otherwise accidentally trigger something when typing a message.

**Comment by yoporla** [comment]
I tried rebinding it to a different key and it does the same thing

**Comment by Lailloken** [comment]
Which keys have you tried?

After clicking ` apply & restart `, was the custom key showing correctly in the edit-field?
![image](https://github.com/user-attachments/assets/d9f69cf9-a80b-4330-82b6-d96883d22e63)

**Comment by yoporla** [comment]
I tried the "=" key and apply & restarted as you mentioned, the key worked it just bring the links to wiki over and over again

**Comment by Lailloken** [comment]
Okay, I tried it. It seems there are a few keys where AutoHotkey can't tell if you're holding it or not. I'll try to find a workaround for that, but in the meantime you'll have to try a bunch of different keys.

**Comment by yoporla** [comment]
I tried with the "J" key as well but it keep doing the same things

**Comment by Lailloken** [comment]
Okay, something is clearly wrong if that happens with regular letters as well. Have you changed any other setting in the hotkeys section of the tool?

What kind of keyboard are you using, and does it use any software/drivers?
Did you install AutoHotkey recently, or has it been a while? I checked the changelogs and the last three versions had a lot of hotkey-related fixes. Maybe reinstalling could fix this?

Also, could you open the `ini\hotkeys.ini` file, copy everything inside and paste it here?

**Comment by Lailloken** [comment]
Not sure if you're still interested (since you stopped responding), but v1.54.6 includes some omni-key changes that might fix your issue.
