### ISSUE TITLE
ban [unreliable]

### ISSUE THREAD

**Issue by lilmagic45** [Lailloken/Lailloken-UI#432]
My account was recently just banned for "3rd party software" This is the only tool I have ever used with Path of Exile. I used it last league no problem but after a few day this league I've since been banned. Has anyone else been banned lately?

**Comment by Lailloken** [comment]
I'm sorry to hear that. This is the first time somebody claimed they were banned. Could you provide a link to your account?
Also, which features did you use?

**Comment by lilmagic45** [comment]
Here is my profile https://www.pathofexile.com/account/view-profile/lilmagic45 and the only features I used was the one that helped with leveling. I also want to add that I was using an old version of the tool that worked for the last league so maybe that could be why?

**Comment by lilmagic45** [comment]
![Screenshot 2024-07-30 010857](https://github.com/user-attachments/assets/1be99e0f-95f4-43ec-885b-125f8a984103)

**Comment by Lailloken** [comment]
(Sorry for the delayed response, I was walking my dog).
Thanks for providing this information, I really hope your appeal will be accepted.
<br>

> the only features I used was the one that helped with leveling. I also want to add that I was using an old version of the tool that worked for the last league so maybe that could be why?

Hmm, I don't see how the Act-Tracker feature could possibly get you flagged in their system. All it does is read the game's client.txt log-file and send gem regex-strings.
***
<br>

I now have to do my own investigation and contact support for my own sanity.

**Comment by mas0ny1** [comment]
Hey @Lailloken,
Let us know when support gets back to you, thanks :)

**Comment by Lailloken** [comment]
So here's the situation:

- this is the first ban-report I have received in two and a half years (i.e. since publishing this tool)

  - the affected account was created shortly before Necropolis league

    ![image](https://github.com/user-attachments/assets/164f9dc3-5562-40c9-bb9b-c8ee8bd28c97)

  - the user was only using the Act-Tracker feature, which interacts with the game by means of reading the client.txt log-file and copying/pasting clipboard data
<br>

- I tried to ask GGG-support whether the user was flagged for these usage-patterns, or something else entirely (even though I knew they probably wouldn't be able to disclose that)

  - that was indeed the case: they can't disclose information about other users

    ![ggg support](https://github.com/user-attachments/assets/4cf01add-6596-42c9-84f6-e19a961134a7)
<br>

- so I did some digging because I couldn't make sense of the situation

  - out of curiosity, I checked the user's GitHub account and found this bug-report: https://github.com/Jire/Overwatcheat/issues/212

    ![user](https://github.com/user-attachments/assets/b706616a-44f0-4c91-876d-3d9565f8a9c3)
<br>

- nonetheless, to give the user the benefit of the doubt, I deliberately waited three more days in order to see if anything else comes up

  - almost 6.5 days into one of the most played leagues ever, nothing else has come up

  - for context, this is the traffic on this repository for the past two weeks:

    ![image](https://github.com/user-attachments/assets/33766a31-6106-4ff4-92aa-6f961a6b51f7)

  - of course, this traffic-data doesn't translate 1:1 to the number of active users (i.e. people who are actually running the tool)

  - this traffic-data doesn't include active users who update the tool via the built-in updater

  - annectodal evidence: Exile-Leveling traffic shortly before Necropolis recorded about 4000 sessions per day, and in 900 of those the 3rd-party export was used to import the guide into Lailloken UI
<br>

## Conclusion
- I will tag this report as "unreliable" since the user has a history of cheating in online games

- this single report of a ban doesn't line up with the game's current popularity and approximate user-base of my tool

- I want to reaffirm that I strictly follow [GGG's 3rd-party guidelines](https://www.pathofexile.com/developer/docs/index#policy)

- I'm indifferent to what people do online and I won't judge, it's just unfortunate to get dragged into something like this

**Comment by mas0ny1** [comment]
@Lailloken really appreciate the detailed investigation. Based on that overwatch cheating bug post I'm also convinced they were just cheating (it was my initial impression as well haha)
Appreciate your transparency and investigation :) I wont be using the tool cause it does really help me (im doing sanctums) but its still awesome how many features the tool has

**Comment by GoodCharles** [comment]
@Lailloken , I truly applaud you for the investigation. Thank you so much for this tool and for strictly following GGG's guidelines.
