### ISSUE TITLE
Cannot use Search-Strings for Bestiary

### ISSUE THREAD

**Issue by aasmall** [Lailloken/Lailloken-UI#441]
Repro:
1. create search strings entry calibrated to the Bestiary page of the challenges pane.
2. test, both positive and negative screen checks work
3. open bestiary page of challenges pane, click omni-key.

Expected:
enters search string in "filter beasts"

Actual:
nothing happens

-----
Interestingly enough, if I open a vendor pane at the same time as the bestiary page, it works great

![image](https://github.com/user-attachments/assets/d6894d82-8467-47c0-9191-929de69c7d95)

**Comment by Lailloken** [comment]
This is happening because the "instance info" is still visible in the top-right corner:

![image](https://github.com/user-attachments/assets/4e651bce-057e-432d-add0-5ae8f0b42fc9)

The "gamescreen" pixel-check is positive, so the tool assumes you're controlling your character and pressed the omni-key to use a skill. It's a general limitation of the search-strings feature, and _I think_ the bestiary index is currently the only in-game search that's neither full-screen nor inventory-related by default. So every time you want to search for beasts, you'll have to open the inventory first.

Sorry about the confusion, there's a note about this limitation in the wiki but it was at the very end of the entry. I moved right to the top and I will also add a note to the settings menu to prevent confusion in the future.

**Comment by aasmall** [comment]
Ah, no worries - Opening my inventory is way easier than finding a vendor. thanks for the explanation.
