### ISSUE TITLE
Old version of Sanctum overlay available?

### ISSUE THREAD

**Issue by Yekci** [Lailloken/Lailloken-UI#455]
Hi, first of all thank you for this great tool! As an avid PoE'er and developer myself this tool is amazing. And I'm eagerly following issue https://github.com/Lailloken/Lailloken-UI/issues/438 as the data representation is really interesting.

I've come across a Reddit post of yours posted some 20 months ago, highlighting an interesting way of quickly showing the room names within Sanctum: https://www.reddit.com/r/pathofexile/comments/zmrird/llkui_experimental_sanctum_cheatsheet_overlay/.

Is there any version of this still around? I prefer the one above to the current one for a number of reasons:

1. Faster showing of notes. From the short demonstration video it seems to be near instant, whereas the current cheat sheet overlay tool (the advanced one) takes around a second to scan sometimes.
2. (Seemingly) just the omni-key was required to show the blue names I think? Now I have to hold a second button (alt/shift/ctrl) in addition to the omni-key, which feels awkward. I don't use the tool for anything else yet, so a second keypress feels unneeded.
3. Purely cosmetically, the current box appears where the mouse is instead of in the 'room information panel' like in the video. Personally I find the old solution more appealing.

Edit: one more reason I prefer the old way is my laziness: it looks like you just held the omni-key and moved it along room info panels, whereas now I have to let go of the hotkey combination and press them again when I'm on another room.

**Comment by Yekci** [comment]
To get around the 'multiple hotkeys' problem I bound the omni-key to my L-Alt, which helps. However some room types (I think ones most to the top) aren't recognized and when I hold L-Alt, my entire PC begins lagging so much, my FPS drops in the single digits for 5 to 10 seconds. I have a 7800X3D CPU paired with a 4090 so that surprised me.

![Uploading poe_llk.png…]()

**Comment by Lailloken** [comment]
- No, the old version no longer exists

- the key-combination is necessary because the omni-key doesn't trigger anything while the instance-info is visible in the top-right corner (game-screen pixel-check)

- the cheat-sheet toolkit, and advanced sheets especially, were an experiment I have kinda lost interest for (since it's rather niche)

- the scanning issues you're experiencing right now are one of many reasons why I didn't expand the toolkit's functionality: it's just too inconsistent and depends on too many variables. It's not worth putting any more time into it when full functionality cannot be guaranteed

- it's probably not a good idea to bind the omni-key to a modifier, let alone cross-binding two hotkeys

**Comment by Yekci** [comment]
I see, thank you for responding. In any case the Sanctum room planner would be an immense addition so I'll be looking forward to that and just memorizing the room names. Have a good one!
