### ISSUE TITLE
overlay interrupts shift+clicking with currency

### ISSUE THREAD

**Issue by hootpocket** [Lailloken/Lailloken-UI#457]
For example when I am rolling an item with alterations and holding shift+clicking. the overlay randomly becomes my computers main window( idk best term for that) and cancels me holding shift with the currency and I have to reselect the alterations.
I don't have shift-clicking activates item-info window active, and i didn't press the omni button. theres no pop-up when it happens.
Sorry, not sure the best way to word that but keeps happening.

**Comment by Lailloken** [comment]
I can't replicate this behavior. The shift-click activation toggles work as intended for both the item-info and map-info tooltips. If they're disabled, they don't influence shift-clicking at all on my end.

Does this also happen if you right-click alts without holding shift -> hold shift -> click items? Because my shift-click feature only activates if you shift-right-click currency and then click items.

Are you using custom in-game keybinds by any chance? For example showing advanced item-info on SHIFT instead of the default ALT?

**Comment by hootpocket** [comment]
It seems only when I shift then right click the currency, seems fine if I right click it first like you said. Thought because I had the item-info shift option off it wouldn't of been why, sorry.
Is there anyway to completely just turn off item-info then? Not a big deal if not since I know the issue now. 
Appreciate the fast answer!

**Comment by hootpocket** [comment]
![image](https://github.com/user-attachments/assets/2a793132-10cf-498d-910b-104848bac32e)
When you say open item-info and shift-click currency + apply you mean this item-info right? 
Same thing, as long as am holding shift before right clicking the currency randomly it will make my screen "flicker" (like flashing the overlay i assume) and deselect the currency because the window lost focus.
by checkbox-toggle, you mean the check for "shift-clicking activates item-info"? tried that same thing, if something else sorry don't see it.
Ever since I updated the newest ahk 1 (and installed ahk 2 same), and this Lailloken ive been having extremely long load times too. Not blaming your ahk, just maybe its somehow related to something outside Lailloken, and is just some weird ahk issue

sorry, i know its hard to help, im not too worried about it personally unless you really wanted to solve it. I don't mind turning it off while not mapping
