### ISSUE TITLE
[REQUEST] - modification of feature 

### ISSUE THREAD

**Issue by Kazatel** [Lailloken/Lailloken-UI#6]
Hi , thank you for nice job, I really like what you have done so far.

This are just ideas , don't get me wrong :)

1) for bookmarked recipes, is it possible to do drag drop, or some order management, so you don't need to break whole tree to make an order? Still not sure how to use it, what have higher priority to finish recipe, you said to put biggest on the bottom if I am right. 
2) I would remove prioritize recipes after scanning, instead of that added highlight or counter to bookmarked recipes, so we can safe some space -move function to highlight components here
3) some button to highlight any component not needed in bookmarked recipes, so I can easily burn something I don't need
4) set how many of some components are needed to be stored in order to make a recipe , so if counter is crossed you can burn the component as you already have few in stock

thanks a lot :)

**Comment by Lailloken** [comment]
1. I will include better documentation with the next release on how priority works. There will be an update on the system.
2. I don't exactly understand what you mean. Maybe take a screenshot and visualize what you mean.
3. Ah, you mean single components to destroy?
4. Are inventories still overflowing despite the tool continually suggesting recipes? So you mean an indicator that says "you have X number of XYZ mod more than you need at the moment"?

**Comment by Kazatel** [comment]
2) you put prioritize recipe after scan, so you have bookmarked recipe basically twice, I would maybe include some counter, like one before and one after, to show you how many you have , and how many you may create and add search for all bookmarked recipies, I liked a way how it worked before, so i could sort it, now component highlight works only after the scaning. 
![Screenshot 2022-02-16 193128_2](https://user-images.githubusercontent.com/19363695/154332548-40f56ea3-2146-4b9d-b7c6-92368bcf6265.png)
3) for example opulent is not part of any recipe and any other component not related to my bookmarked recipes 
4) If it is possible for example I would like to make 2x lunaris touched  so script count how many of components I need, then it will start showing me it as not needed in step in above button, so I can burn it as I have enough in stock

**Comment by ExecutedOnce** [comment]
Heya just wanted to piggyback off this. I would also love if the (NOT PRIORITIZED) didn't include mods that are used at all in my bookmarks (even if the mods already exist). 

As an example, [SOUL EATER] requires [GARGANTUAN], I'm not sure if it's because I have one [SOUL EATER] already made, but it tells me I can use gargantuan in [READY (NOT PRIORITIZED)] recipes. Though I generally want to save any mod/single-mod used in my (PRIORITIZED) recipes and not use them in the (NOT PRIORITIZED) crafting.  

Or maybe a more simple way of putting it, I'd generally only like to use mods/single-mods that aren't used in (PRIORITIZED), whether or not I already have a few of the bookmarked mods.

Though maybe it would be easier to just lightly overlay mod icons in the Archnemesis stash with a 30% opacity green/yellow for (PRIORITIZED) and a red for (NOT USED AT ALL IN PRIORITIZED).

**Comment by Kazatel** [comment]
![Screenshot 2022-02-16 193128_3](https://user-images.githubusercontent.com/19363695/154430732-52624e5a-0585-4964-bd0b-eae49998b601.jpg)
Looks like I missed something important, I could just add Innocent touched to bookmark , and then sub-recipies start showing after the scan in (PRIORITIZED), which is good.

What i am missing right now the most is option to clink on bookmarked recipe to highlight components and general overview of how many components i do have.
this leads to stock of many components (example having 5 steel infused) and stock of some components I need for bookmarked recipe but not that much :D.
I thought some counter could be place somewhere either to recipe scheme or to bookmarks.

Maybe hoovering on bookmarked recipe with 1second delay to show scheme and left click to highlight components or right click. Not sure what is easiest way to script.

for me personally would be nice if I add innocent touch it will automatically add this whole combo to bookmarks, so I can see.
Showing schem is ok , but as I said, I am missing highlight for components when recipe is not ready yet. 

Please , all I wrote are just my ideas what I would do if be capable :D. I verry appreciate your doing as without it , I would spend 5mins of sorting infront each nem tower.

**Comment by Lailloken** [comment]
> Heya just wanted to piggyback off this. I would also love if the (NOT PRIORITIZED) didn't include mods that are used at all in my bookmarks (even if the mods already exist).
> 
> As an example, [SOUL EATER] requires [GARGANTUAN], I'm not sure if it's because I have one [SOUL EATER] already made, but it tells me I can use gargantuan in [READY (NOT PRIORITIZED)] recipes. Though I generally want to save any mod/single-mod used in my (PRIORITIZED) recipes and not use them in the (NOT PRIORITIZED) crafting.
> 
> **Or maybe a more simple way of putting it, I'd generally only like to use mods/single-mods that aren't used in (PRIORITIZED), whether or not I already have a few of the bookmarked mods. An option for this would be great, as I mainly want to keep all my prioritized components.**
> 
> Though maybe it would be easier to just lightly overlay mod icons in the Archnemesis stash with a 30% opacity green/yellow for (PRIORITIZED) and a red for (NOT USED AT ALL IN PRIORITIZED).
> 
> I supposed another option would be to just have a 'prioritize x number of mods where 0 = infinite', as someone else had suggested.

The next update will address most of these issues. I meant to release it yesterday, but I had less time to work on it than anticipated. I ~should~ be able to finish it today once I get home.

Short summary:
- the script will suggest ready recipes in a way that completes a whole set in the prio-list the fastest, i.e. it actively keeps track of sub-component status and re-allocates priorities
   - there will be a list of the type and number of base mods required to finish the whole prio-list; I include this since there is reliable information now on how to somewhat target-farm bases (I'll incorporate that info in some form in the future)
   - currently, it would only be able to track one 'set' of the prio-list; I don't know if I can implement user-configurable set sizes in time, but I at least have a short-term workaround in mind
- it will prevent suggesting recipes that use base components from prio-recipes (the current behavior is an oversight)
- I think I will add an additional button to the letter bar that highlights (in-game search) base mods not included in the prio-list, recipes that don't affect the prio-list will continue to show up in ready (not prio)

**Comment by Lailloken** [comment]
> Looks like I missed something important, I could just add Innocent touched to bookmark , and then sub-recipies start showing after the scan in (PRIORITIZED), which is good.

Yeah, that's on my part. I should have documented the change from bookmark to priority better. The priority list is supposed to be the set of four mods that you do at the very end, "the big wombo-combo". The ready suggestions help you get there faster.

> What i am missing right now the most is option to clink on bookmarked recipe to highlight components and general overview of how many components i do have. this leads to stock of many components (example having 5 steel infused) and stock of some components I need for bookmarked recipe but not that much :D. I thought some counter could be place somewhere either to recipe scheme or to bookmarks.

I thought about adding counters but decided against it. I don't really know why anymore. I'll think about it again. I removed highlighting from the prio-list because I thought it was unnecessary to check it over and over -- you'll know when it's ready from the suggestions -- and now you can check in the tree-view.

> for me personally would be nice if I add innocent touch it will automatically add this whole combo to bookmarks, so I can see. Showing schem is ok , but as I said, I am missing highlight for components when recipe is not ready yet.

Why are you highlighting recipes that are not ready yet? If you do it to save the components from being used in an non-prio recipe, this will be fixed in the next update. If it's not that, please tell me. I need to know why and how something is used before implementing (or going back to) it.

**Comment by Kazatel** [comment]
`EDIT: adding all components of a prioritized recipe will bloat the window really fast.`
it's true, could be fixed with lowering fonts , to fit a bit more

`Why are you highlighting recipes that are not ready yet? If you do it to save the components from being used in an non-prio recipe, this will be fixed in the next update. If it's not that, please tell me. I need to know why and how something is used before implementing (or going back to) it.`

The only reason is there is no counter yet or set size for components, so sometimes I do have a lot of same type but missing others. Randomly checking how many I do have and sort them for some uncompleted recipes. I sort the inventory saving two/three on bottom and remaining I put on top, then I burn them. Typing specific component to search how many I have is more difficult then clicking on bookmarked recipe. I stayed with older version for longer time, because there it worked the way I liked. :) 

in general, not sure how to achieve this all functionality together and not bloat the window. Only what came to my mind is , add this to scheme??? but then scheme need to be permanent on screen by click and you need extra button to close it.
What I mean you click on bookmarked recipe and that show scheme where you can click on base component to search specific component only  or on recipe to search set of components needed to finish specific recipe.
That could bring previous functionality back while remain easy to read. Just my thoughts.

**Comment by Lailloken** [comment]
reported issues and solutions -- summary:
- mods that are part of the prio-list are being suggested in burn pile: fixed
- prio-list surplus handling: implemented, presented by hold-clicking 'prio'-panel
- burn pile for irrelevant mods and recipes: fixed/improved
