### ISSUE TITLE
Press F3 to search for modifiers

### ISSUE THREAD

**Issue by OmikronGamma** [Lailloken/Lailloken-UI#64]
Hello, this message, "Press F3 to search for modifiers" is stuck on my screen whenever i press press omni-button on cluster jewel and press on "crafting table" option.
If i press F3, my character uses skills and quest menu pops-up.

**Comment by Lailloken** [comment]
Does that option not open your browser with the crafting table from poedb loaded up? It's supposed to work like this:
- click 'crafting table' -> browser loads up the table on poedb
- you press F3 to use the browser's search function to automatically highlight the cluster jewel's type/enchant -> the tooltip should go away

I could add a time-out in the next release to remove the tooltip after a few seconds, but that would be kind of redundant since you're only supposed to use this feature to look up specific cluster jewels, not cluster jewels in general. But let me know if your browser does indeed not load up; something else is wrong if that's the case.

**Comment by OmikronGamma** [comment]
Browser indeed being open, but. Sometimes after i use this feature, i stay in the game (i will lookup whatever i needed on poedb, but later), and there is a unhidable pop-up in the middle of my screen.

**Comment by Lailloken** [comment]
> Id rather the tool open up cluster's corresponding size page (large, medium, small)

Do you mean [these pages](https://poedb.tw/us/Small_Cluster_Jewel#SmallClusterJewelEnchantmentModifiers)? I didn't know they existed. I only implemented the search because the general cluster jewel page was so long and cluttered. Yeah, it's probably better to link to the corresponding size.

I can also change the F3 thing to timing out whenever the user tabs back into the game. It's really old code from my initial, personal version of the script before archnemesis, and I have never reworked it since.

Should I split the context-menu options into 'crafting table: all' and 'crafting table: corresponding size'? This way, one could do broader searches and more specific ones, like you suggested.

**Comment by OmikronGamma** [comment]
> I can also change the F3
I would like it to be a settings option to be honest; not a big fan of game tool to do work in my browser.

> Should I split the context-menu options into 'crafting table: all' and 'crafting table: corresponding size'? This way, one could do broader searches and more specific ones, like you suggested.
Sounds good.

**Comment by Lailloken** [comment]
> I would like it to be a settings option to be honest; not a big fan of game tool to do work in my browser.

Fair enough. I'll make it an option in the general section of the settings menu, something along the lines of "enable browser features" which can be disabled if desired.

Thanks for your input on cluster jewels. It's an area that comes a bit short on my side because I use them so rarely (that's also why I needed the search in the first place because I always forget which types are good for the kinds of builds I play). I also play SSF only, so that's why this feature is built so one-dimensional: find a jewel -> check which passives that specific jewel can roll and if it's worth keeping.

**Comment by Lailloken** [comment]
Implemented the discussed changes into v1.25.1. I'll keep this issue open for now so you can provide more feedback if needed. Feel free to close this issue if everything works OK.

**Comment by OmikronGamma** [comment]
Looks great so far, gonna close both tickets. Thank you.
