### ISSUE TITLE
1.26.4 Elegant Hubris Default Display Issue on 4k monitors

### ISSUE THREAD

**Issue by Cleista** [Lailloken/Lailloken-UI#79]
The list of notables for Elegant Hubris is so long the list goes offscreen by default (and the tooltip highlight also goes offscreen). 
![image](https://user-images.githubusercontent.com/67157844/179345128-5c0dac8b-590d-4133-bca1-da563652f64e.png)

Not sure if this affects other resolutions as well. Would it be possible to display this as 2 columns or use a smaller font size by default?

**Comment by Lailloken** [comment]
This happens due to the display scaling settings in Windows. I forced the script to override these in the past, but it doesn't seem to work anymore. I'll add options to scale the seed explorer font separately. In the meantime, you'll have to change the font settings for the whole script in the settings menu to correct this issue.

**Comment by Lailloken** [comment]
I have implemented fixes in v1.26.4-hotfix. I'll leave this issue open for now in case something else related to this comes up.
