### ISSUE TITLE
v1.27.1 Issues with custom keybinds on PoE

### ISSUE THREAD

**Issue by maixmi** [Lailloken/Lailloken-UI#84]
I have inventory binded to C and when I press omni-key my inventory also opens (because seems omni-key sends Alt-Ctrl-C) closing for example betrayal window. Character screen (default on C) does not react to Alt-Ctrl-C but pretty much everything else does.

Also having 'highlight items' binded to Shift I have to manually edit the script to get advanced info from items. Bit compatibility issues here and there because custom binds.

Noticed small typo on line 2303 while trying to get gwennen redex string to work
`	SendInput, ^{a}{v}`

**Comment by Lailloken** [comment]
Hmm, that's a problem. I'm able to replicate this. It's really weird that it doesn't trigger the character screen but other actions. It also only closes the inventory when there's no item underneath the cursor. And all of this is seemingly not script-related -- it happens with or without it when trying to copy something to clipboard. I'll need to see what I can do about that.

Yeah, the Gwennen thing is a typo. Thanks for reporting.

**Comment by Lailloken** [comment]
Okay, I have some ideas how to tackle these issues. For whatever reason, advanced mod descriptions is not bound to ALT but rather tied to 'highlight items and objects', which is re-bindable. Funny thing is, the official patch notes for 3.1.2 said this: 
> There's now a UI option called "Advanced Mod Descriptions" which shows additional information about items when you press Alt.

So I don't know if this can be considered a bug or miscommunication, or if they just assumed no one would rebind ALT. I can fix that specific issue by adding an option to specify which key highlighting is bound to, so that the omni-key sends keybind-Ctrl-C instead.

As for the other issue: it seems that if there's no item info to copy when pressing Ctrl-C, the game client registers a key-event for C and triggers whatever is bound to it -- unless it's the character screen. That's just bizarre. I can't do any testing or work on that until tomorrow, so this will have to wait, unfortunately.

**Comment by Lailloken** [comment]
OK, update. I don't think there's a straightforward way to fix the issue with the C-key because of how the client behaves. The only way I can fix it script-wise is implementing an option to split the omni-key into two different hotkeys: one for item-related features, and one for the rest. So you'd have the option to bind the part of the omni-key that requires item-info to a different key and keep the main part (that triggers betrayal, Gwennen, etc.) on the middle mouse-button (or wherever you have it).

To me personally, this feels kind of weird from a user-experience standpoint, but let me know what you think. The only other solution would be rebinding inventory to something else other than C and retraining your muscle memory. The fix shouldn't be much work to implement, so don't worry about that when deciding.

**Comment by maixmi** [comment]
Opinion to bind different hotkeys sounds good for me since i've been using keybinds like this for decades.

**Comment by Lailloken** [comment]
I have just released v1.27.2 with a fix to the Gwennen-regex and workarounds for custom keybinds. I'll leave this issue open for now, so you can report any additional problems you may encounter.
