### ISSUE TITLE
Activate POE after pressing omni key to make it more "safe"?

### ISSUE THREAD

**Issue by gobacktogo** [Lailloken/Lailloken-UI#89]
hey,
just downloaded Lailloken-UI. looks very impressive, thanks for sharing!

one thing i noticed right away: if i press the omni-key, while the menu is open, most key presses do not get registered by POE (flasks, movementskill, guardskill etc.), 

would it be possible to activate the POE window after bringing up the omni-key menu, just to make this thing more safe? lets say i press the omni key on an item in my inventory, only to notice that i am standing in some random degen ground effect. pressing my life flask wont register. i first have to click in the POE screen to use any keybinds.

thanks!

**Comment by Lailloken** [comment]
It closes as soon as the PoE-client is activated, so one can close it by clicking somewhere else, without having to click an option or press ESC (just like the context-menu in Windows). If I take that out and activate the client after opening context-menu, the user will be forced to click an option or press ESC.

Which feature are you trying to access in the middle of a map? Just curious because I've kinda lost track what's in there, but I don't think there's anything that would be accessed mid-map. Maybe I'm missing something here.

**Comment by gobacktogo** [comment]
yea, i guess the chances for this to RIP a char are astronomically low.
